# Práctico 1: Aprendizaje Automático.
## Diplodatos Kaggle Competition
<h3><FONT COLOR="#FF0000"> Alumno: Flavio Olivier (Omega)</FONT></h3>

#### El plan es recorrer el campo 'Description' y traducir a english aquellos textos que están en otros idiomas para luego aplicarles alguna técnica de PLN.

In [1]:
#librerias...

import numpy as np
import pandas as pd
import re

In [2]:
#levantamos train y test originales...

train_df = pd.read_csv('data/train.csv')
test_df = pd.read_csv('data/test.csv')

display(train_df.head(), test_df.head())

,Type,Age,Breed1,Breed2,Gender,Color1,Color2,Color3,MaturitySize,FurLength,Vaccinated,Dewormed,Sterilized,Health,Quantity,Fee,State,Description,AdoptionSpeed,PID
0,2,3,299,0,1,1,7,0,1,1,2,2,2,1,1,100,41326,Nibble is a 3+ month old ball of cuteness. He ...,2,0
1,1,4,307,0,2,1,2,0,2,1,1,1,2,1,1,150,41401,"Good guard dog, very alert, active, obedience ...",2,3
2,1,1,307,0,1,1,0,0,2,1,2,2,2,1,1,0,41326,This handsome yet cute boy is up for adoption....,2,4
3,2,3,266,0,2,5,6,0,2,1,2,2,2,1,1,0,41326,This is a stray kitten that came to my house. ...,2,5
4,2,12,264,264,1,1,0,0,2,3,2,2,3,1,1,300,41326,anyone within the area of ipoh or taiping who ...,1,6

,Type,Age,Breed1,Breed2,Gender,Color1,Color2,Color3,MaturitySize,FurLength,Vaccinated,Dewormed,Sterilized,Health,Quantity,Fee,State,Description,PID
0,2,1,265,0,1,1,2,0,2,2,3,3,3,1,1,0,41401,I just found it alone yesterday near my apartm...,1
1,1,1,307,0,1,2,7,0,2,2,1,1,2,1,1,0,41326,Their pregnant mother was dumped by her irresp...,2
2,1,0,307,0,2,1,2,7,2,1,2,2,2,1,6,0,41326,Siu Pak just give birth on 13/6/10 to 6puppies...,7
3,2,12,265,0,2,1,7,0,2,2,3,3,3,1,1,0,41326,"Very manja and gentle stray cat found, we woul...",9
4,2,3,264,0,2,1,2,5,3,3,1,1,2,1,1,50,41326,Kali is a super playful kitten who is on the g...,11

In [3]:
#para remover emojis y rarezas en 'Description'...
import re

emoji_pattern = re.compile("["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map symbols
        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           "]+", flags=re.UNICODE)

In [4]:
#language Translator...
from googletrans import Translator
import time

In [5]:
#identificamos 'Description' NO 'english' y 'horrores' en train_df...

for index, row in train_df.iterrows():
    translator = Translator() #objetotTranslator.
    
    try:
        descrip = emoji_pattern.sub(r'', row['Description'])
        translated_train_df = translator.translate(descrip)
        
        if translated_train_df.src != 'en':
            #print('original:', row['Description'])
            #print('idioma origen:', translated_train_df.src)
            #print('idioma destino:', translated_train_df.dest)
            #print('traducción:', translated_train_df.text)
            train_df.loc[index, 'lang'] = translated_train_df.src
            print('Traduciendo fila:{}'.format(index))
            train_df.loc[index, 'Description'] = translated_train_df.text
        else:
            train_df.loc[index, 'lang'] = 'en'
    except:
        print('horror: ({}) {}'.format(index, row['Description']))
        train_df.loc[index, 'lang'] = 'xx'
        train_df.loc[index, 'Description'] = np.nan
        
    time.sleep(2)
    #input('pausa')

Traduciendo fila:8
Traduciendo fila:24
Traduciendo fila:27
Traduciendo fila:64
horror: (66) nan
Traduciendo fila:74
Traduciendo fila:79
Traduciendo fila:82
Traduciendo fila:90
Traduciendo fila:118
Traduciendo fila:161
Traduciendo fila:175
Traduciendo fila:202
Traduciendo fila:205
Traduciendo fila:221
Traduciendo fila:280
Traduciendo fila:311
Traduciendo fila:359
Traduciendo fila:368
Traduciendo fila:387
Traduciendo fila:390
horror: (419) nan
Traduciendo fila:441
Traduciendo fila:533
Traduciendo fila:563
Traduciendo fila:616
Traduciendo fila:628
Traduciendo fila:648
Traduciendo fila:655
Traduciendo fila:664
Traduciendo fila:668
Traduciendo fila:695
Traduciendo fila:702
Traduciendo fila:748
Traduciendo fila:752
Traduciendo fila:784
Traduciendo fila:802
Traduciendo fila:818
Traduciendo fila:827
Traduciendo fila:888
Traduciendo fila:908
Traduciendo fila:912
Traduciendo fila:983
Traduciendo fila:985
Traduciendo fila:1018
Traduciendo fila:1025
Traduciendo fila:1034
Traduciendo fila:1051
Traduciendo fila:1068
Traduciendo fila:1081
Traduciendo fila:1116
Traduciendo fila:1174
Traduciendo fila:1190
Traduciendo fila:1199
Traduciendo fila:1218
Traduciendo fila:1270
Traduciendo fila:1327
Traduciendo fila:1358
Traduciendo fila:1361
Traduciendo fila:1388
Traduciendo fila:1418
Traduciendo fila:1423
Traduciendo fila:1436
Traduciendo fila:1480
Traduciendo fila:1549
Traduciendo fila:1603
Traduciendo fila:1611
Traduciendo fila:1612
Traduciendo fila:1640
Traduciendo fila:1663
Traduciendo fila:1690
Traduciendo fila:1692
Traduciendo fila:1703
Traduciendo fila:1745
Traduciendo fila:1746
Traduciendo fila:1788
Traduciendo fila:1837
Traduciendo fila:1870
Traduciendo fila:1875
Traduciendo fila:1878
Traduciendo fila:1889
Traduciendo fila:1891
Traduciendo fila:1919
Traduciendo fila:1959
Traduciendo fila:1979
Traduciendo fila:2049
Traduciendo fila:2052
Traduciendo fila:2063
Traduciendo fila:2117
Traduciendo fila:2131
Traduciendo fila:2132
Traduciendo fila:2155
Traduciendo fila:2156
Traduciendo fila:2160
Traduciendo fila:2173
Traduciendo fila:2189
Traduciendo fila:2203
Traduciendo fila:2213
Traduciendo fila:2257
Traduciendo fila:2263
Traduciendo fila:2276
Traduciendo fila:2296
Traduciendo fila:2297
Traduciendo fila:2334
Traduciendo fila:2381
Traduciendo fila:2382
Traduciendo fila:2421
Traduciendo fila:2445
Traduciendo fila:2463
Traduciendo fila:2487
Traduciendo fila:2490
Traduciendo fila:2502
Traduciendo fila:2546
Traduciendo fila:2564
Traduciendo fila:2573
Traduciendo fila:2590
Traduciendo fila:2592
Traduciendo fila:2610
Traduciendo fila:2660
Traduciendo fila:2697
Traduciendo fila:2714
Traduciendo fila:2801
Traduciendo fila:2826
Traduciendo fila:2846
Traduciendo fila:2854
Traduciendo fila:2890
Traduciendo fila:2942
Traduciendo fila:2975
horror: (2977) nan
Traduciendo fila:3049
Traduciendo fila:3075
Traduciendo fila:3095
Traduciendo fila:3097
Traduciendo fila:3113
Traduciendo fila:3141
Traduciendo fila:3149
Traduciendo fila:3160
Traduciendo fila:3173
Traduciendo fila:3216
Traduciendo fila:3236
Traduciendo fila:3262
Traduciendo fila:3287
Traduciendo fila:3296
Traduciendo fila:3306
Traduciendo fila:3310
Traduciendo fila:3324
Traduciendo fila:3344
Traduciendo fila:3357
Traduciendo fila:3369
Traduciendo fila:3389
Traduciendo fila:3396
Traduciendo fila:3413
Traduciendo fila:3449
Traduciendo fila:3513
Traduciendo fila:3526
Traduciendo fila:3535
Traduciendo fila:3632
Traduciendo fila:3641
Traduciendo fila:3663
Traduciendo fila:3715
Traduciendo fila:3725
Traduciendo fila:3732
Traduciendo fila:3733
Traduciendo fila:3753
Traduciendo fila:3775
Traduciendo fila:3784
Traduciendo fila:3802
Traduciendo fila:3829
Traduciendo fila:3833
Traduciendo fila:3839
Traduciendo fila:3858
Traduciendo fila:3860
Traduciendo fila:3876
Traduciendo fila:3880
Traduciendo fila:3910
Traduciendo fila:3929
Traduciendo fila:3930
Traduciendo fila:3969
Traduciendo fila:4009
Traduciendo fila:4024
Traduciendo fila:4038
Traduciendo fila:4077
Traduciendo fila:4089
Traduciendo fila:4096
Traduciendo fila:4162
Traduciendo fila:4171
Traduciendo fila:4203
Traduciendo fila:4231
Traduciendo fila:4234
Traduciendo fila:4260
horror: (4265) nan
Traduciendo fila:4268
Traduciendo fila:4275
Traduciendo fila:4289
Traduciendo fila:4291
Traduciendo fila:4322
Traduciendo fila:4371
Traduciendo fila:4378
Traduciendo fila:4432
Traduciendo fila:4453
Traduciendo fila:4468
Traduciendo fila:4484
Traduciendo fila:4491
Traduciendo fila:4547
Traduciendo fila:4562
Traduciendo fila:4581
Traduciendo fila:4613
Traduciendo fila:4666
Traduciendo fila:4668
Traduciendo fila:4723
Traduciendo fila:4858
Traduciendo fila:4883
Traduciendo fila:4899
Traduciendo fila:4922
Traduciendo fila:4949
Traduciendo fila:4991
Traduciendo fila:5010
Traduciendo fila:5019
Traduciendo fila:5090
Traduciendo fila:5094
Traduciendo fila:5112
Traduciendo fila:5117
Traduciendo fila:5122
Traduciendo fila:5213
Traduciendo fila:5287
Traduciendo fila:5290
Traduciendo fila:5318
Traduciendo fila:5334
Traduciendo fila:5341
Traduciendo fila:5344
Traduciendo fila:5345
Traduciendo fila:5356
Traduciendo fila:5360
Traduciendo fila:5450
Traduciendo fila:5489
Traduciendo fila:5501
Traduciendo fila:5522
Traduciendo fila:5536
Traduciendo fila:5558
Traduciendo fila:5571
Traduciendo fila:5599
Traduciendo fila:5606
Traduciendo fila:5608
Traduciendo fila:5617
Traduciendo fila:5637
Traduciendo fila:5666
Traduciendo fila:5682
Traduciendo fila:5705
Traduciendo fila:5739
Traduciendo fila:5746
Traduciendo fila:5788
Traduciendo fila:5811
Traduciendo fila:5828
Traduciendo fila:5836
Traduciendo fila:5848
Traduciendo fila:5850
Traduciendo fila:5881
Traduciendo fila:5905
Traduciendo fila:5913
Traduciendo fila:5989
Traduciendo fila:5996
Traduciendo fila:6015
Traduciendo fila:6017
Traduciendo fila:6018
Traduciendo fila:6081
Traduciendo fila:6138
horror: (6162) nan
Traduciendo fila:6168
Traduciendo fila:6181
Traduciendo fila:6193
Traduciendo fila:6245
Traduciendo fila:6295
Traduciendo fila:6325
Traduciendo fila:6341
Traduciendo fila:6363
Traduciendo fila:6417
Traduciendo fila:6457
Traduciendo fila:6478
Traduciendo fila:6504
Traduciendo fila:6530
Traduciendo fila:6606
Traduciendo fila:6608
Traduciendo fila:6624
Traduciendo fila:6657
Traduciendo fila:6688
Traduciendo fila:6696
Traduciendo fila:6814
Traduciendo fila:6836
Traduciendo fila:6884
Traduciendo fila:6895
Traduciendo fila:6915
Traduciendo fila:6920
Traduciendo fila:6944
Traduciendo fila:7072
Traduciendo fila:7073
Traduciendo fila:7082
Traduciendo fila:7146
Traduciendo fila:7151
Traduciendo fila:7170
Traduciendo fila:7207
Traduciendo fila:7210
Traduciendo fila:7231
Traduciendo fila:7264
Traduciendo fila:7266
Traduciendo fila:7281
Traduciendo fila:7287
Traduciendo fila:7291
Traduciendo fila:7294
Traduciendo fila:7305
Traduciendo fila:7306
Traduciendo fila:7341
Traduciendo fila:7439
Traduciendo fila:7487
Traduciendo fila:7509
Traduciendo fila:7522
Traduciendo fila:7572
Traduciendo fila:7592
Traduciendo fila:7601
Traduciendo fila:7615
Traduciendo fila:7631
Traduciendo fila:7648
Traduciendo fila:7650
Traduciendo fila:7664
Traduciendo fila:7709
Traduciendo fila:7740
Traduciendo fila:7742
Traduciendo fila:7836
Traduciendo fila:7910
Traduciendo fila:7916
Traduciendo fila:7988
Traduciendo fila:8012
Traduciendo fila:8025
Traduciendo fila:8041
Traduciendo fila:8053
Traduciendo fila:8068
Traduciendo fila:8092
Traduciendo fila:8109
Traduciendo fila:8112
Traduciendo fila:8135
Traduciendo fila:8139
Traduciendo fila:8176
Traduciendo fila:8246
Traduciendo fila:8262
Traduciendo fila:8269
Traduciendo fila:8279
Traduciendo fila:8284
Traduciendo fila:8298
Traduciendo fila:8317
Traduciendo fila:8334
Traduciendo fila:8359
Traduciendo fila:8364
Traduciendo fila:8365
Traduciendo fila:8374
horror: (8382) For more pics go here: 9th April edit: I have revised the adoption fee to RM to include the fee I paid her breeder. The reason I am now making reimbursement of the breeder's fee compulsory is to help out Malaysian Dogs Deserve Better (MDDB) - they are currently in dire financial straits (read this for details and please help if you can: ). Previously if Donut's adopter voluntarily reimbursed the breeder's fee I had planned to donate the RM to MDDB anyway, since they really need funding I reckon a sincere adopter won't mind the expense as it's going to a good cause. 6th April edit: The family who intended to adopt Donut backed out due to personal reasons (hectic things going on in their lives, nothing to do with Donut herself). So this bundle of beagle-y joy is up for adoption again! :) 5th March edit: I have had people contact me asking if she's old enough to mate. Apparently some people can't read - DONUT HAS BEEN SPAYED. Meaning she can't get pregnant. If you want to adopt her with the intention of breeding her, don't bother contacting me. Donut is an affectionate beagle that loves human and canine company. Trained to do toileting on grass and knows a few tricks - sit, paw, high five, up, down, stand, responds to her name and stays on command in the presence of food. Well socialised and impervious even to thunderstorms (she will calmly snooze under whichever car's in the porch whereas my adult dog will be running around in a panic)! She has some good and bad traits typical of beagles. The good: She's a pack animal as beagles are bred to be and therefore gets along well with other dogs (plays happily with my lab pup and even my temperamental adult mutt). Very friendly even with new people - strangers are constantly delighted when they approach her. The bad: She loves digging holes in the garden (a common problem with beagles). So if you love gardening and your lawn must look immaculate she is not the dog for you. She will also chew stuff you leave lying around which is typical behaviour for all teething puppies. 9th April edit: This isn't necessarily a good/bad thing as it's a natural inclination due to her breed (beagles were originally bred to hunt), but forgot to mention, Donut has a high prey drive when it comes to small animals and cannot be trusted unsupervised with them. She has killed squirrels and birds that wandered into my garden so if you have small animals as pets in your home (rabbits/hamsters/sugar gliders etc.) she would not be a good fit. She's curious and friendly with adult cats when supervised but I would not advise keeping her if you have kittens as I'm not sure if she might mistake them for prey to hunt due to their small size. For those who might wonder why this lovely dog is up for adoption: She is the product of an irresponsible breeder - I'd rather not go into details because remembering how she came into being in my care makes me mad =/ Initially I was hoping to keep her but being a person who believes one should spend a lot of quality time with his/her dog, I've reluctantly come to the conclusion that with 2 dogs of my own I just cannot give Donut the attention she deserves. I spend at least 2 hours a day with my dogs - my opinion is that if you only have time to feed your dog and give it a quick pat as you leave for work/return, then you do not have enough time for a dog. I hope she will find a loving home where love can be lavished on her instead of her present situation where she is receiving limited attention. Adoption fee is for covering her vaccination (she has had the full set of shots) and spaying costs. On top of those expenses I had to pay off the breeder to have Donut released to me (otherwise the breeder would have dumped her at SPCA or pawned her off to the first willing buyer who may have turned out to be a backyard breeder). If you are a serious adopter and able to reimburse me for the breeder's fee (RM) this would be greatly appreciated - I will donate the reimbursed amount to a dog rescue organisation. [PLEASE NOTE the 9th April edit on top of this listing - the breeder's fee is now compulsory.) I am going to be blunt and state upfront that I can afford to be very selective about the home she goes to and will be. After all, pedigreed dogs are more popular (I wish more people would love mixed breeds just as much, but this is the unfortunate reality) and I am in no hurry rehome her. My priority is finding Donut a home where she will receive more love and attention than I can give her at the moment. Bearing the above in mind, these are my conditions for adoption: 1. You MUST have time for her. Donut thrives on attention - when I first fostered her she had separation anxiety and would whine and howl if there were no humans or dogs to keep her company (with training she is now a confident dog). As such I strongly prefer a home where there is a friendly dog for companionship. If Donut will be the only dog in the household, I would prefer if the household has someone able to give her constant attention (i.e. retiree/homemaker/work-at-home/kids). 2. No tying or caging up (unless you find a constantly howling beagle particularly enjoyable....). 3. Adoption fee of RM to cover medical costs and breeder's fee. 4. Patience with destructive behaviour that is inevitable with all puppies. 5. Maintain her on a premium kibble (she is currently on Orijen)/raw food diet. 6. Allow me to visit in the beginning to check on her wellbeing (as such I am looking for adopters in the KL/Selangor area so that this is possible). 7. Lavish her with love, love and more love! :) I would appreciate it if you could email a brief intro of yourself, your experience with dogs if any, which area you live in, your household situation (what type of home you live in, whether you have other family members/friends living with you etc.) and why you would like to adopt Donut. I will get back to you with my contact number for further discussion.

Traduciendo fila:8396
Traduciendo fila:8397
Traduciendo fila:8432
Traduciendo fila:8527
Traduciendo fila:8534
Traduciendo fila:8535
Traduciendo fila:8563
Traduciendo fila:8573
Traduciendo fila:8587
Traduciendo fila:8590
Traduciendo fila:8592
Traduciendo fila:8594
Traduciendo fila:8598
Traduciendo fila:8604
Traduciendo fila:8613
Traduciendo fila:8628
Traduciendo fila:8631
Traduciendo fila:8644
Traduciendo fila:8666
Traduciendo fila:8673
Traduciendo fila:8681
Traduciendo fila:8718
Traduciendo fila:8737
Traduciendo fila:8743
Traduciendo fila:8749
Traduciendo fila:8757
Traduciendo fila:8779
Traduciendo fila:8780
Traduciendo fila:8785
Traduciendo fila:8807
Traduciendo fila:8812
Traduciendo fila:8865
Traduciendo fila:8872
Traduciendo fila:8882
Traduciendo fila:8892
Traduciendo fila:8919
Traduciendo fila:8928
Traduciendo fila:8968
Traduciendo fila:8978
horror: (8987) nan
Traduciendo fila:8997
Traduciendo fila:9023
Traduciendo fila:9059
Traduciendo fila:9067
Traduciendo fila:9076
Traduciendo fila:9081
Traduciendo fila:9082
Traduciendo fila:9092
Traduciendo fila:9095
Traduciendo fila:9097
Traduciendo fila:9124
Traduciendo fila:9145
Traduciendo fila:9164
Traduciendo fila:9165
Traduciendo fila:9168
Traduciendo fila:9172
Traduciendo fila:9224
Traduciendo fila:9288
Traduciendo fila:9292
Traduciendo fila:9294
Traduciendo fila:9295
Traduciendo fila:9382
Traduciendo fila:9446
Traduciendo fila:9450
Traduciendo fila:9485
Traduciendo fila:9516
Traduciendo fila:9524
Traduciendo fila:9547
Traduciendo fila:9570
Traduciendo fila:9603
Traduciendo fila:9606
Traduciendo fila:9627
Traduciendo fila:9653
Traduciendo fila:9755
Traduciendo fila:9768
Traduciendo fila:9934
Traduciendo fila:9940
Traduciendo fila:10037
Traduciendo fila:10089
Traduciendo fila:10111
Traduciendo fila:10113
Traduciendo fila:10122
Traduciendo fila:10133
Traduciendo fila:10150
Traduciendo fila:10162
Traduciendo fila:10165
Traduciendo fila:10171
Traduciendo fila:10217
Traduciendo fila:10222
Traduciendo fila:10232
Traduciendo fila:10242
Traduciendo fila:10263
Traduciendo fila:10303
Traduciendo fila:10336
Traduciendo fila:10338
Traduciendo fila:10345
Traduciendo fila:10364
Traduciendo fila:10374
Traduciendo fila:10385
Traduciendo fila:10417
Traduciendo fila:10443
Traduciendo fila:10481
Traduciendo fila:10486
Traduciendo fila:10499
Traduciendo fila:10503
Traduciendo fila:10506
Traduciendo fila:10512
Traduciendo fila:10526
Traduciendo fila:10543
Traduciendo fila:10555
Traduciendo fila:10572

In [14]:
train_df.loc[train_df['lang'] != 'en']

,Type,Age,Breed1,Breed2,Gender,Color1,Color2,Color3,MaturitySize,FurLength,...,Dewormed,Sterilized,Health,Quantity,Fee,State,Description,AdoptionSpeed,PID,lang
8,1,3,307,0,2,2,5,7,2,2,...,3,3,1,1,0,41401,"Lost Dog Found (Bandar Menjalara, Kepong/Taman...",2,14,zh-CN
24,2,1,266,0,1,1,0,0,1,1,...,2,2,1,1,0,41361,female tatO to male ... child to mother or not,1,31,id
27,2,2,265,0,2,2,0,0,1,2,...,2,2,1,1,0,41326,this cute one needs someone who can love it. s...,1,37,ms
64,2,24,266,0,1,4,0,0,3,1,...,2,2,2,1,0,41324,I found this cat coming home. There may be peo...,3,93,ms
66,2,19,285,0,2,1,6,0,3,3,...,1,2,1,1,0,41401,NaN,1,96,xx
74,2,2,265,0,1,3,0,0,1,2,...,2,2,1,1,0,41401,"healthy, playfull and very spoiled.",2,105,id
79,2,12,299,0,2,3,6,7,2,2,...,2,1,1,2,0,41324,"Cheap, cute, and understanding orgasms.",4,111,ms
82,2,1,266,0,2,2,5,7,2,1,...,1,3,1,1,0,41326,DIDO female. Discharged at the eateries. Still...,1,119,ms
90,2,3,266,0,3,1,7,0,2,2,...,3,3,1,2,0,41326,This mother & the kitten belongs to the neighb...,1,131,ms
118,1,1,307,0,2,2,5,7,3,1,...,1,3,1,1,0,41401,Dear all dog lovers~ I'm helping my friend to ...,2,168,zh-CN
161,2,4,288,285,2,1,7,0,1,3,...,2,3,1,1,250,41326,cats type ragdoll mix persian :) - betina - da...,2,225,ms
175,1,36,307,0,2,2,0,0,2,1,...,1,1,1,1,0,41326,A survivor from Dry Straits.,3,250,id
202,2,6,265,266,2,2,5,0,2,2,...,2,2,1,1,0,41401,"with the weight of his heart, he had to let go...",1,291,ms
205,2,20,265,0,1,1,6,7,3,2,...,1,2,1,1,0,41326,Chiko active cats. He has 6 fingers and has a ...,1,295,ms
221,2,2,265,0,1,1,7,0,1,2,...,2,2,1,1,0,41401,Lost and homeless. It's time to throw a cat in...,4,317,ms
280,2,7,266,0,1,6,7,0,2,1,...,1,2,1,2,0,41326,my cat adopt it to be kept before you can be n...,4,400,ms
311,2,12,265,265,2,1,0,0,2,2,...,1,2,1,1,0,41401,KUCING KUCING DIBA .. SANGAT MANJA. NOW MIDDLE...,3,451,ms
359,2,1,266,0,2,2,7,0,1,1,...,2,2,1,1,0,41326,I take this idle kitten in front of a shop. He...,4,525,ms
368,2,12,266,0,3,1,4,7,3,1,...,1,1,1,5,0,41401,There are 5 cats for adoption. They are the id...,4,542,ms
387,2,5,266,0,2,1,2,6,2,1,...,2,2,1,1,0,41401,This champion knows!,2,566,id
390,2,4,266,265,1,1,5,0,2,2,...,1,2,1,1,0,41327,Kittens to be given for free. Male kitten aged...,3,570,ms
419,2,2,264,0,1,1,7,0,2,2,...,2,2,1,1,0,41401,NaN,4,605,xx
441,2,14,299,0,1,3,0,0,3,1,...,1,1,1,1,0,41326,"very obedient, know her name, spoiled, get alo...",2,635,id
533,2,1,265,0,1,1,7,0,2,2,...,3,3,1,1,0,41326,"kittens to be treated, I met with / without my...",1,757,ms
563,2,8,292,0,3,1,4,7,2,1,...,1,3,1,2,0,41367,Mek som and Pok Leh. The special feature of po...,4,803,ms
616,2,1,266,0,3,2,6,0,1,1,...,2,2,1,2,0,41332,These 2 were left alone at staircase next to o...,3,874,ms
628,2,12,266,0,1,1,7,0,3,2,...,1,2,1,1,0,41326,cute and spoiled very .. heard say .. look amb...,4,888,ms
648,2,2,266,0,3,1,4,6,1,1,...,2,2,1,3,0,41326,Momi cat was born at my doorstep last month (3...,2,914,ms
655,2,2,266,0,1,3,7,0,1,2,...,1,2,1,1,0,41326,the little boy came in front of the door of th...,2,926,ms
664,2,6,266,0,1,1,7,0,1,1,...,2,2,1,1,0,41326,Tigger's another sibling. A very good cat. Lik...,2,938,ms
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,2,2,266,0,1,6,7,0,1,1,...,3,3,1,1,0,41401,Little Spring Roll is looking for forever Home...,2,14320,zh-CN
10133,2,12,265,0,1,3,7,0,2,2,...,1,2,1,1,100,41401,pampered. strong cravings can eat cabbage,4,14333,ms
10150,2,2,265,0,2,1,4,7,3,2,...,1,3,1,1,40,41326,GOLD was born at / in the grocery store. I sav...,1,14354,ms
10162,1,4,307,0,1,1,7,0,2,1,...,1,1,1,1,0,41326,Cheer is wandering near my place. We are tryin...,4,14383,zh-CN
10165,2,1,265,266,2,1,2,7,1,1,...,2,2,1,1,0,41401,I found a cat near my college tv room. Maybe s...,1,14389,ms
10171,1,1,307,0,3,2,7,0,2,1,...,2,2,1,3,0,41326,2male 1female puppies for free. Location at ja...,1,14397,ms
10217,1,1,307,0,2,1,2,6,2,2,...,2,2,1,2,0,41327,2 mixed breed very cute female puppies found n...,2,14468,zh-CN
10222,2,3,264,0,3,1,2,3,1,3,...,2,2,1,3,150,41326,Hamtaro and Gooffy - parents who are parents (...,2,14478,ms
10232,1,1,307,0,3,1,5,7,3,1,...,2,1,1,4,0,41336,"Have been adopted, expect them to be happy in ...",1,14489,zh-CN
10242,2,10,266,0,1,2,0,0,3,1,...,3,3,1,1,0,41332,Choco. Cats coming in alone. Let the 2-3 days ...,2,14505,ms
10263,2,4,266,0,2,1,4,7,1,1,...,2,2,1,1,0,41326,I jumped them this side street near my house. ...,4,14537,ms
10303,1,60,307,0,1,1,3,0,2,1,...,3,3,1,1,0,41401,My Name:Daisy Lim Contact Number: Please don't...,4,14593,zh-CN
10336,1,48,307,307,2,1,0,0,2,1,...,2,2,1,1,0,41401,"*PETALING JAYA* Hello, my name is Kopi. The na...",4,14643,zh-CN
10338,2,6,266,0,1,1,5,6,2,1,...,1,2,1,1,0,41326,Location: IIum / UIA Gombak (text / call / wha...,4,14647,la
10345,1,2,307,307,1,1,2,7,2,1,...,2,2,1,1,0,41326,"Location: Teluk Intan, Perak",4,14656,ms
10364,2,24,266,0,3,2,7,0,3,1,...,1,2,1,4,0,41326,-Had been given frontline and dewormed -Si mot...,1,14683,ms
10374,2,12,292,0,2,2,5,0,2,2,...,1,2,1,1,0,41332,Meet the doorstep ... Don't know who left it ....,3,14698,id
10385,2,4,265,0,2,1,4,7,3,2,...,2,3,1,1,0,41326,Aci is the same as Acu I saved. Aci is rather ...,2,14711,id
10417,1,2,307,0,2,5,7,0,2,1,...,1,1,1,1,0,41401,"Cute puppies for adoption, looking a forever H...",2,14756,zh-CN
10443,2,8,266,266,3,1,6,0,1,1,...,1,1,1,4,0,41326,Can someone give a child a home? Just saved in...,4,14798,zh-CN
10481,2,2,266,0,1,3,7,0,2,1,...,1,2,1,1,0,41332,"Dumped behind our shop, Jimmy Neutron (coz he ...",1,14849,ms
10486,2,2,265,0,2,3,0,0,1,2,...,3,3,1,1,0,41326,Kitten for adopt is free. Walking around the h...,2,14858,ms
10499,2,9,264,276,1,5,0,0,2,3,...,1,1,1,1,200,41330,DaH,3,14875,ms
10503,2,17,264,0,1,7,0,0,2,2,...,1,2,1,1,200,41326,Salam ... sy nak lets cat Domestic Long Hair t...,4,14881,ms
10506,2,3,265,265,3,1,2,7,2,2,...,2,2,1,6,0,41326,I ade 5 cats..5 kitty (3 months) who are looki...,4,14884,ms
10512,2,4,265,0,1,4,0,0,2,2,...,3,3,1,1,25,41336,To be given a little bit of food for another C...,2,14894,ms
10526,2,1,266,0,3,1,3,0,2,2,...,2,2,1,4,0,41336,Anyone interested can contact me. Batu Pahat A...,4,14910,ms
10543,2,3,265,0,2,6,7,0,2,2,...,2,2,1,1,0,41326,very active and spoiled ...,4,14934,id
10555,2,2,265,0,2,1,0,0,1,2,...,1,2,1,1,0,41324,This cat is found by a friend in front of a gr...,2,14951,ms
10572,2,84,264,264,3,1,7,0,2,2,...,1,1,1,2,50,41326,hey there are 2 cats that have long been defen...,3,14976,ms

In [12]:
train_df.loc[train_df['lang'] == 'xx']

,Type,Age,Breed1,Breed2,Gender,Color1,Color2,Color3,MaturitySize,FurLength,...,Dewormed,Sterilized,Health,Quantity,Fee,State,Description,AdoptionSpeed,PID,lang
66,2,19,285,0,2,1,6,0,3,3,...,1,2,1,1,0,41401,NaN,1,96,xx
419,2,2,264,0,1,1,7,0,2,2,...,2,2,1,1,0,41401,NaN,4,605,xx
2977,2,84,266,0,1,3,0,0,3,1,...,1,1,1,1,0,41401,NaN,2,4218,xx
4265,2,3,254,254,2,2,7,0,1,1,...,2,3,1,2,0,41326,NaN,3,6041,xx
6162,2,2,299,0,2,1,7,0,2,1,...,1,2,1,1,0,41326,NaN,2,8674,xx
8382,1,7,20,0,2,1,2,7,2,1,...,1,1,1,1,500,41326,NaN,3,11843,xx
8987,1,7,109,0,1,3,0,0,3,2,...,1,1,1,1,250,41326,NaN,1,12713,xx

In [65]:
train_df['lang'].value_counts()

en       10117
ms         319
zh-CN       99
id          27
xx           7
la           7
sl           2
hr           2
mg           1
haw          1
Name: lang, dtype: int64

In [60]:
#limpiamos train_df...
train_df.loc[train_df['lang'] == 'xx', 'Description'] = np.nan

#generamos 'Description_clean' sin emojis...
train_df['Description_clean'] = train_df['Description'].str.replace('[^\w\s#@/:%.,_-]', '', flags = re.UNICODE)

#... backupeamos en disco.
train_df.to_csv('data/train_en.csv', header = True, index_label = 'ind')

In [5]:
#identificamos 'Description' NO 'english' y 'horrores' en test_df...

for index, row in test_df.iterrows():
    translator = Translator() #objetotTranslator.
    
    try:
        descrip = emoji_pattern.sub(r'', row['Description'])
        translated_test_df = translator.translate(descrip)
        
        if translated_test_df.src != 'en':
            #print('original:', row['Description'])
            #print('idioma origen:', translated_test_df.src)
            #print('idioma destino:', translated_test_df.dest)
            #print('traducción:', translated_test_df.text)
            test_df.loc[index, 'lang'] = translated_test_df.src
            print('Traduciendo fila:{}'.format(index))
            test_df.loc[index, 'Description'] = translated_test_df.text
        else:
            test_df.loc[index, 'lang'] = 'en'
    except:
        print('horror: ({}) {}'.format(index, row['Description']))
        test_df.loc[index, 'lang'] = 'xx'
        test_df.loc[index, 'Description'] = np.nan
        
    time.sleep(2)
    #input('pausa')

Traduciendo fila:61
Traduciendo fila:78
Traduciendo fila:92
Traduciendo fila:103
Traduciendo fila:124
Traduciendo fila:129
Traduciendo fila:146
Traduciendo fila:153
Traduciendo fila:155
Traduciendo fila:180
Traduciendo fila:186
Traduciendo fila:193
Traduciendo fila:198
Traduciendo fila:223
Traduciendo fila:227
Traduciendo fila:250
Traduciendo fila:288
horror: (323) nan
Traduciendo fila:358
Traduciendo fila:400
Traduciendo fila:425
Traduciendo fila:520
Traduciendo fila:561
horror: (629) nan
Traduciendo fila:665
Traduciendo fila:681
Traduciendo fila:703
Traduciendo fila:704
Traduciendo fila:708
Traduciendo fila:726
Traduciendo fila:732
Traduciendo fila:733
Traduciendo fila:758
Traduciendo fila:762
Traduciendo fila:849
Traduciendo fila:856
Traduciendo fila:889
Traduciendo fila:895
Traduciendo fila:949
Traduciendo fila:961
Traduciendo fila:1010
Traduciendo fila:1102
Traduciendo fila:1106
Traduciendo fila:1117
Traduciendo fila:1125
Traduciendo fila:1127
Traduciendo fila:1134
Traduciendo fila:1147
Traduciendo fila:1171
Traduciendo fila:1183
Traduciendo fila:1244
Traduciendo fila:1254
Traduciendo fila:1256
Traduciendo fila:1263
Traduciendo fila:1349
Traduciendo fila:1364
Traduciendo fila:1432
horror: (1433) nan
Traduciendo fila:1459
Traduciendo fila:1470
Traduciendo fila:1478
Traduciendo fila:1491
Traduciendo fila:1497
Traduciendo fila:1550
Traduciendo fila:1551
Traduciendo fila:1567
Traduciendo fila:1604
Traduciendo fila:1606
Traduciendo fila:1611
Traduciendo fila:1673
Traduciendo fila:1705
Traduciendo fila:1735
Traduciendo fila:1741
Traduciendo fila:1780
Traduciendo fila:1792
Traduciendo fila:1798
Traduciendo fila:1813
Traduciendo fila:1839
Traduciendo fila:1845
Traduciendo fila:1881
Traduciendo fila:1892
Traduciendo fila:1929
Traduciendo fila:1952
Traduciendo fila:1958
Traduciendo fila:1980
Traduciendo fila:2009
Traduciendo fila:2018
Traduciendo fila:2100
Traduciendo fila:2162
Traduciendo fila:2171
Traduciendo fila:2177
Traduciendo fila:2180
Traduciendo fila:2271
Traduciendo fila:2278
Traduciendo fila:2290
horror: (2331) It was late at night when I was about to leave from work when I heard loud meowings near my car. I did not have the heart to leave it there as I saw no signs of its mother nearby. So I took it home and fed it with some food and gave it a quick wash. I went to the vet next day and bought a bottle and milk for cats and it has been drinking from the bottle. Not only is he playful and adorable, he is also quite clever as he has been pee-ing at the same place (in a shoe box laid with newspapers). He is always cleaned afterwards. A very friendly and active little guy, purrs almost all the time now especially after being fed (even knows where he can get his milk from!). Unfortunately, my wife and I are not able to look after him as we are both working until late night. We would like to find a home for this little guy, with or without a foster mother cat, as he can already be fed using a bottle, and can already eat soft food. As much as we are already attached to this little fella, we know that being in a house with caring people to look after him, he'd be much better off without a couple of busy people like us. And we would be happy to see him grow with love and become a handsome cat. ----- Updating again after we gave Sim away to his new family. My husband and I cried our eyes out from missing him last night. I still feel all choked up when I look at his pictures and videos. The night my husband brought him in, we didn't have anything suitable to feed a kitten with but an ikan goreng. As desperate as he was, we had to give him something to eat, so ikan goreng it was. And a few drops of Dutch Lady's full cream milk. The next day, we had only planned to drop him at a local vet, in hoping that a good samaritan would take him in, but the clerk said they don't take animals in, so we ended up buying the little fella a bottle and 2 boxes of milk for cats. Since then we had been feeding him the milk. We left Sim at home and when we came back later that night, we saw him sitting quietly at one spot. And we also saw spots of white vomit and yellow-ish liquidy stool. After immediately cleaning him up, Sim looked sleepy. I thought he might be tired from vomiting like humans would. So I wrapped him up and cuddled him. After a while, I thought something was strange about him. Usually he would wake up if there was even a slight movement, this time he didn't even stir. I also noticed that he squirted liquid from his rectum while he was sleeping. It was night, no vets would still be open. So I read up a website, at which describes a condition of a kitten from its stool and urine's color and texture. I suspected that he might be suffering from food poisoning (the ikan goreng and the Dutch Lady milk). I was devastated thinking that Sim might not last that night as his body was so weak, his head just lolled if unsupported, his paws were almost cold, all the signs I though that he was really dying. I couldn't bear the thought of seeing him die all by myself as my husband was at work at that time. All I could do that night was rub him to keep him warm and pray that he'd be ok. I was already so smitten by this kitten, although we couldn't keep it, I really wanted it to live. Miraculously, my prayers were answered when Sim suddenly got up, eyes wide open and started roaming the room. I was like "were you playing tricks on me?". It was really miraculous! I couldn't explain it if it's actually normal but I was extremely grateful. I still am today. After the gruesome experience, we went the extra mile to look after him, like looking after a human baby. Brought him a proper food for kitten, took him to the vet when he didn't pee and poo one whole day. As it turns out, he was still too young to pee on his own, so whenever he wanted to pee, he would let out signs which I finally figured out that if when he is meowing but wanted neither food nor milk, I would put him in the shoebox, stimulate him and if he didn't resist, he would proceed to pee until he is done. At first I have mixed feelings about touching an animal at its genitals but after the first time and seeing how at ease he felt, it really made me feel like a momcat. In those six days we took care of him, we were quite surprised that a lot of people were asking for him from this advert. For that, thank you all for your interest, it really meant a lot to us. The morning before we gave him up, I decided to give him a little wash. As I know that all cats hate cold water, I bathed him in warm water and he LOVED it, didn't squirm, didn't kick around, didn't scratch me for putting him in such a spot! At one point, I thought he wanted to immerse himself in the water. Haha! And then I wrapped him up and he fell asleep again before I fed him one last time. Throughout the one hour journey to his new owner, Sim just slept away. We really think that he is so much like a human baby who would fall asleep in car rides because of the aircond and the feeling of the car moving. :) Sim Sim... After handing him over, the new owner has been keeping in touch with us to ask what should she do if Sim is giving certain signs. I felt a bit worried if Sim's signs were misread, and all those sort of stuff a mom would typically be worried of. Text messages from the new owner saying that he likes to climb on top of people and follow them around the house, all the things Sim did to us showed us that he is settled at his new home and his new family. I tell myself that he'll be alright. It's weird that I have kittens at my parents' place but none made me feel like Sim did. None made me feel so emotionally attached like Sim made me feel. Though he might not even know us, what more remember us, we pray that he'll grow happily and healthily. Thank you Sim for the wonderful experience you have given us.
Traduciendo fila:2332
Traduciendo fila:2347
Traduciendo fila:2358
Traduciendo fila:2370
Traduciendo fila:2377
Traduciendo fila:2379
Traduciendo fila:2385
Traduciendo fila:2386
Traduciendo fila:2389
Traduciendo fila:2391
Traduciendo fila:2405
Traduciendo fila:2427
Traduciendo fila:2440
Traduciendo fila:2442
Traduciendo fila:2464
Traduciendo fila:2474

Traduciendo fila:2509
Traduciendo fila:2514
Traduciendo fila:2536
Traduciendo fila:2568
Traduciendo fila:2587
Traduciendo fila:2602
Traduciendo fila:2606
Traduciendo fila:2624
Traduciendo fila:2635
Traduciendo fila:2665
Traduciendo fila:2742
Traduciendo fila:2762
Traduciendo fila:2766
Traduciendo fila:2784
Traduciendo fila:2790
Traduciendo fila:2815
Traduciendo fila:2855
Traduciendo fila:2871
Traduciendo fila:2872
Traduciendo fila:2933
horror: (2965) nan
Traduciendo fila:2991
Traduciendo fila:3062
Traduciendo fila:3071
Traduciendo fila:3113
Traduciendo fila:3147
Traduciendo fila:3158
Traduciendo fila:3163
Traduciendo fila:3205
Traduciendo fila:3272
Traduciendo fila:3276
horror: (3316) nan
Traduciendo fila:3325
Traduciendo fila:3334
Traduciendo fila:3372
Traduciendo fila:3423
Traduciendo fila:3441
Traduciendo fila:3451
Traduciendo fila:3486
Traduciendo fila:3535
Traduciendo fila:3539
Traduciendo fila:3568
Traduciendo fila:3653
Traduciendo fila:3662
Traduciendo fila:3670
Traduciendo fila:3778
Traduciendo fila:3798
Traduciendo fila:3834
Traduciendo fila:3865
Traduciendo fila:3904
Traduciendo fila:3931
Traduciendo fila:3934
Traduciendo fila:3975
Traduciendo fila:3995
Traduciendo fila:4027
Traduciendo fila:4038
Traduciendo fila:4055
Traduciendo fila:4070
Traduciendo fila:4081
Traduciendo fila:4083
Traduciendo fila:4086
Traduciendo fila:4137
Traduciendo fila:4138
Traduciendo fila:4142
Traduciendo fila:4145
Traduciendo fila:4195
Traduciendo fila:4234
Traduciendo fila:4257
Traduciendo fila:4278
Traduciendo fila:4287
Traduciendo fila:4312
Traduciendo fila:4329
Traduciendo fila:4331
Traduciendo fila:4333
Traduciendo fila:4340
Traduciendo fila:4358
horror: (4360) nan
Traduciendo fila:4386
Traduciendo fila:4396
Traduciendo fila:4408

In [6]:
test_df.loc[test_df['lang'] != 'en']

,Type,Age,Breed1,Breed2,Gender,Color1,Color2,Color3,MaturitySize,FurLength,Vaccinated,Dewormed,Sterilized,Health,Quantity,Fee,State,Description,PID,lang
61,2,2,266,254,2,1,4,7,1,1,2,2,2,1,1,0,41326,Momi cat was born at my doorstep last month (3...,214,ms
78,2,12,247,0,1,1,6,7,2,2,1,1,1,1,1,0,41326,Noizy from a MIX BITCH MIX | Noizy's from MIX ...,264,ms
92,2,4,266,0,1,1,2,4,2,1,2,2,2,1,1,0,41326,This is the baby siblings. She's spoiled. It's...,305,ms
103,1,18,307,307,2,1,0,0,2,1,1,1,1,1,1,0,41326,He is a baby who was thrown in the industrial ...,358,zh-CN
124,2,18,265,0,2,5,7,0,2,1,2,2,2,1,1,0,41401,Found around the beautiful island of klang. Ha...,411,ms
129,2,1,266,0,3,2,4,7,2,2,1,1,2,1,20,0,41401,"Hi, to anyone who is interested to adopt cats ...",427,ms
146,2,1,266,0,3,1,2,6,2,1,2,1,2,1,2,0,41326,The cat was abandoned by the mother and after ...,473,ms
153,2,2,266,0,2,1,6,7,1,2,3,3,3,1,1,0,41326,kitten in 2-3 months ... stray and xde cat mot...,499,ms
155,2,6,266,0,2,1,2,7,1,1,1,1,1,1,3,0,41401,kucing stray yang lola jaga..dlu lepaskn kurun...,506,ms
180,2,19,266,266,1,6,0,0,2,1,1,1,1,1,2,0,41326,Can someone give a child a home? Experience in...,571,zh-CN
186,2,1,285,264,1,1,7,0,3,3,2,2,2,1,1,50,41326,Found around the office in Bandar Baru Bangi b...,611,ms
193,2,2,265,0,2,1,7,0,1,2,2,2,2,1,1,0,41401,ank cat is so cute and very spoiled ... hrap2 ...,631,ms
198,2,3,264,265,2,1,2,3,1,2,2,1,2,1,1,0,41326,Why her name i put deaf? Because he always mak...,671,ms
223,2,1,266,0,2,1,4,7,1,1,2,2,2,1,1,0,41326,I take this idle kitten in front of a shop. He...,755,ms
227,2,8,266,266,2,1,2,0,2,1,2,2,2,1,1,0,41332,Lady Black is approximately 8 to 9 months old....,766,ms
250,2,2,264,0,3,1,3,7,1,3,2,2,2,1,5,0,41326,Greetings. Hi. I have 4 kittens and one cat mo...,836,ms
288,2,2,266,0,2,1,3,7,2,1,2,2,2,1,1,10,41336,The little leopard is a two-month-old girl. He...,1002,zh-CN
323,2,6,266,292,1,1,6,0,1,1,1,1,3,1,1,0,41326,NaN,1098,xx
358,2,36,285,0,1,7,0,0,2,2,3,3,3,1,1,0,41401,guava,1195,id
400,2,12,266,0,2,1,7,0,2,1,2,1,2,1,7,0,41330,kiki is very active. white cat itam die. yello...,1334,id
425,2,1,266,266,2,1,2,7,1,1,2,2,2,1,1,50,41326,Cute kitten. -brown to find a new master-very ...,1415,ms
520,1,48,179,0,1,5,7,0,1,2,1,1,1,1,1,0,41401,"Found him at a park in Seri Petaling, Kuala Lu...",1761,ms
561,2,3,266,0,3,1,5,7,1,1,2,2,2,1,3,0,41401,3 small pet for adoption. That's pretty cute. ...,1883,ms
629,1,31,307,0,2,1,2,7,2,2,1,1,1,1,2,0,41401,NaN,2109,xx
665,2,4,266,0,1,1,7,0,1,1,1,1,2,1,2,0,41324,"Hi, I have two kittens that are saved and have...",2214,ms
681,2,6,285,265,1,1,7,0,3,2,2,1,2,1,1,0,41326,"mom mix persian and dad domestic cat, fur more...",2262,ms
703,2,2,265,0,3,1,2,5,1,1,2,2,2,1,3,0,41332,"3 kittens to be adopted. 2 male, 1 female. Sel...",2371,ms
704,1,24,307,0,1,2,7,0,2,3,3,3,3,3,1,0,41330,"JOHOR, Kulai (Around INDAHPURA ) Have You Seen...",2377,zh-CN
708,2,6,265,0,2,3,7,0,2,3,1,1,2,1,1,0,41325,I found this cat at the diner. I want to find ...,2382,ms
726,2,1,266,0,1,2,6,7,2,1,2,2,2,1,2,0,41332,2 very young kittens dumped behind our shop in...,2472,ms
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3931,1,1,307,307,1,1,2,0,2,2,2,2,2,1,1,0,41326,"Please Help Share, Thank You. Who is going to ...",13441,zh-CN
3934,2,19,266,266,1,4,0,0,2,1,1,1,1,1,1,0,41326,Can someone give a child a home? Experience in...,13445,zh-CN
3975,2,2,266,0,2,1,7,0,2,1,2,1,2,1,1,0,41326,Kitten still breastfeeding. Be released at age...,13592,ms
3995,2,1,243,0,1,1,2,7,1,1,2,2,2,1,1,0,41326,CHILDREN KUCING FREE ADOPTION Color: spt dlm i...,13682,ms
4027,2,7,266,0,2,2,6,0,2,1,2,1,2,1,1,0,41326,Spoiled and active,13773,id
4038,2,2,265,0,1,4,7,0,2,2,2,1,3,1,1,0,41326,ArBut. Sekor kitten that I found body got whit...,13798,ms
4055,2,3,266,266,3,1,6,7,2,2,3,3,3,1,6,0,41401,I have many cats in the house until the neighb...,13870,ms
4070,2,14,266,292,1,2,5,0,2,1,1,2,2,1,1,0,41326,Toilet trained..very manjer & slalu mintak duk...,13916,jw
4081,2,7,254,266,2,1,4,7,2,1,1,1,1,1,1,50,41326,Indoor and outdoor (just out of the garden onl...,13951,ms
4083,2,1,266,0,1,1,2,7,1,1,2,2,2,1,1,0,41326,I take this kitten in front of a shop. The kit...,13953,ms
4086,2,3,266,0,1,1,6,7,1,1,2,2,2,1,1,0,41326,Tommy is very cute and pretty hair A bit shy a...,13962,ms
4137,2,24,265,288,1,1,5,7,3,2,3,3,3,1,1,0,41401,"this is coco, my lovely cat, coco is nice, coc...",14134,ms
4138,2,5,265,0,2,1,6,0,2,2,2,1,2,1,2,0,41401,"Toilet trained, spoiled. For those who want to...",14141,ms
4142,2,3,266,0,2,2,5,7,2,1,2,1,3,1,1,0,41326,Omey is looking for a new family. Who is willi...,14156,ms
4145,2,2,266,266,3,1,7,0,1,1,2,2,3,1,2,0,41326,Lowey & Tommy age 2 months / already broke up ...,14167,ms
4195,2,3,292,0,2,2,0,0,1,2,2,1,1,1,1,0,41326,Kiki Sgt is spoiled and active.,14314,id
4234,2,3,243,0,2,1,3,7,1,2,1,1,1,1,1,0,41332,Tadaaaa ... this is my latest kitty .. The nam...,14426,ms
4257,2,28,292,0,1,2,0,0,3,2,2,2,3,3,1,0,41330,my cat excident got hit by the car and I sure ...,14490,ms
4278,2,2,266,0,1,1,7,0,1,1,2,2,2,1,1,10,41326,-Happy cute -Like play -Nakal .. -Food and Dry...,14563,ms
4287,2,2,265,0,1,2,0,0,3,2,2,1,3,1,1,0,41326,MILOs are cute and strong eating.,14590,ms
4312,2,12,285,0,2,6,0,0,2,3,2,2,2,1,1,200,41336,Hello malaysian .. I have a cat named gabby to...,14660,ms
4329,2,2,283,283,3,1,6,7,1,2,3,3,3,1,4,0,41326,Cats are given free to those who love cats,14725,ms
4331,2,2,241,0,2,1,2,7,2,2,2,2,3,2,1,0,41336,Meet him at the cafe at UTM Skudai in a dirty ...,14729,ms
4333,1,10,307,307,1,1,2,0,3,1,1,1,1,1,1,0,41326,He is a baby who was thrown in the industrial ...,14737,zh-CN
4340,2,2,266,0,2,3,4,0,1,1,2,2,2,1,1,0,41401,Orange cat girl seeking for support (Kuala Lum...,14761,zh-CN
4358,2,4,266,0,1,2,5,0,2,1,3,3,2,1,1,0,41326,"bebo is very spoiled, cheerful. He is an only ...",14802,id
4360,2,1,266,0,3,2,7,0,1,1,3,3,3,2,4,0,41401,NaN,14809,xx
4386,2,5,266,266,1,7,0,0,1,1,2,2,2,1,1,0,41401,Occhi Belli name given means beautiful eyes. I...,14918,ms
4396,2,12,243,292,1,6,7,0,2,1,2,1,2,2,1,0,41401,the first cat we saved .. dropped in the drain...,14952,ms
4408,1,6,195,0,2,1,7,0,1,3,1,1,2,1,1,0,41401,ooooo,14987,sq

In [7]:
test_df.loc[test_df['lang'] == 'xx']

,Type,Age,Breed1,Breed2,Gender,Color1,Color2,Color3,MaturitySize,FurLength,Vaccinated,Dewormed,Sterilized,Health,Quantity,Fee,State,Description,PID,lang
323,2,6,266,292,1,1,6,0,1,1,1,1,3,1,1,0,41326,NaN,1098,xx
629,1,31,307,0,2,1,2,7,2,2,1,1,1,1,2,0,41401,NaN,2109,xx
1433,2,2,299,0,1,1,7,0,2,1,2,1,2,1,1,0,41326,NaN,4904,xx
2331,2,2,266,0,1,1,7,0,1,1,2,2,2,1,1,0,41326,NaN,8019,xx
2965,1,0,307,0,1,5,7,0,2,2,3,3,3,2,1,0,41326,NaN,10272,xx
3316,2,25,292,292,1,2,0,0,3,1,1,1,1,1,1,0,41326,NaN,11365,xx
4360,2,1,266,0,3,2,7,0,1,1,3,3,3,2,4,0,41401,NaN,14809,xx

In [64]:
test_df['lang'].value_counts()

en       4219
ms        144
zh-CN      26
id         12
xx          7
jw          1
bs          1
sq          1
Name: lang, dtype: int64

In [56]:
#limpiamos train_df...
test_df.loc[test_df['lang'] == 'xx', 'Description'] = np.nan

#generamos 'Description_clean' sin emojis...
test_df['Description_clean'] = test_df['Description'].str.replace('[^\w\s#@/:%.,_-]', '', flags = re.UNICODE)

#... backupeamos en disco.
test_df.to_csv('data/test_en.csv', header = True, index_label = 'ind')