# Practico Mentoria - Analisis Exploratorio y Curación de Datos
<h3><FONT COLOR="#FF0000"> Alumno: Flavio Olivier (Omega)</FONT></h3>

---

### Importaciones

In [1]:
#paquetería...

%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy as sp

from sklearn import preprocessing

import warnings
warnings.filterwarnings('ignore')

In [2]:
# Set seed for reproducibility
np.random.seed(0)

In [3]:
#daterio...

path = 'https://raw.githubusercontent.com/diplodatos2019mentoria/Analisis_Exploratorio_Curacion_Datos/master/'

player_df = pd.read_csv(path + 'Datasets/football_player.csv')
team_df = pd.read_csv(path + 'Datasets/football_team.csv')
match_df = pd.read_csv(path + 'Datasets/football_match.csv')

print("Shape 'player_df' = {}".format(player_df.shape))
print("Shape 'team_df'   = {}".format(team_df.shape))
print("Shape 'match_df'  = {}".format(match_df.shape))

Shape 'player_df' = (11060, 40)
Shape 'team_df'   = (288, 22)
Shape 'match_df'  = (25979, 12)

---

# 1. Importacion de los datos

Calculemos el rango de fechas de los partidos

In [4]:
match_df['date'].max() - match_df['date'].min()

TypeError: unsupported operand type(s) for -: 'str' and 'str'

Indiquemos que la columna `date` es una fechas como indica la [documentación](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#datetime-handling)

In [5]:
# TODO

match_df = pd.read_csv(path + 'Datasets/football_match.csv', parse_dates = ['date'])
match_df['date'].max() - match_df['date'].min()

Timedelta('2868 days 00:00:00')

# 2. Etiquetas de variables/columnas: no usar caracteres especiales

Chequar que no haya caracteres fuera de `a-Z`, `0-9` y `_` en los nombres de columnas de los Dataframes:
* `player_df`
* `team_df`
* `match_df`

In [6]:
# TODO

#caracteres especiales...
import re

def check(col):
    regex = re.match(r'([a-zA-Z0-9_])+$', col)
     
    if regex == None:
        validacion = 'INVALIDO'
    else:
        validacion = 'ok'
    
    return validacion

#side by side...
from IPython.display import display_html

def siamesas(*args):
    html_str = ''
    spaciador = '<table style="min-width: 30px !important;"><tr style="min-width: 30px !important; background:none !important;"><td style="min-width: 30px !important;"></td></tr></table>'
    for df in args:
        html_str += df.to_html() + spaciador
        
    display_html(html_str.replace('table', 'table style = "display:inline"'), raw = True)

In [7]:
#validamos nombres de columnas...

dfs = []
cols = []
estados = []

for df in ['player_df', 'team_df', 'match_df']:
    for col in pd.eval(df + '.columns'):
        #print(df, col, '->', check(col))
        dfs.append(df)
        cols.append(col)
        estados.append(check(col))

dfs = pd.DataFrame.from_dict({'tabla':dfs, 'columna':cols, 'valida':estados})
siamesas(dfs.loc[dfs.tabla == 'player_df'], dfs.loc[dfs.tabla == 'team_df'], dfs.loc[dfs.tabla == 'match_df'])

In [8]:
#reeplazamos espacios por '_'...
#... y re-validamos.

player_df.columns = player_df.columns.str.replace(' ', '_')
team_df.columns = team_df.columns.str.replace(' ', '_')
match_df.columns = match_df.columns.str.replace(' ', '_')

#

dfs = []
cols = []
estados = []

for df in ['player_df', 'team_df', 'match_df']:
    for col in pd.eval(df + '.columns'):
        #print(df, col, '->', check(col))
        dfs.append(df)
        cols.append(col)
        estados.append(check(col))

dfs = pd.DataFrame.from_dict({'tabla':dfs, 'columna':cols, 'valida':estados})
siamesas(dfs.loc[dfs.tabla == 'player_df'], dfs.loc[dfs.tabla == 'team_df'], dfs.loc[dfs.tabla == 'match_df'])

# 3. Agregar nuevas caracteristicas

Agregar al Dataframe `player_df` una nueva columna que sea `imc` correspondiente al **Indice de Masa Corporal**

Link:
* https://www.texasheart.org/heart-health/heart-information-center/topics/calculadora-del-indice-de-masa-corporal-imc/

In [9]:
# TODO

if 'IMC' in player_df.columns:
    player_df.drop('IMC', axis = 1, inplace = True)
    
player_df.insert(4, 'IMC', player_df['weight_kg'] / player_df['height_m']**2)
player_df.head()

,player_name,birthday,height_m,weight_kg,IMC,overall_rating,potential,preferred_foot,crossing,finishing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,Aaron Appindangoye,1992-02-29,1.83,84.82,25.327720,63.60,67.60,right,48.60,43.60,...,53.60,47.60,63.80,66.00,67.80,5.60,10.60,9.60,7.60,7.60
1,Aaron Cresswell,1989-12-15,1.70,66.22,22.913495,66.97,74.48,left,70.79,49.45,...,57.45,53.12,69.39,68.79,71.52,12.18,8.67,14.24,10.36,12.91
2,Aaron Doran,1991-05-13,1.70,73.94,25.584775,67.00,74.19,right,68.12,57.92,...,69.38,60.54,22.04,21.12,21.35,14.04,11.81,17.73,10.12,13.50
3,Aaron Galindo,1982-05-08,1.83,89.81,26.817761,69.09,70.78,right,57.22,26.26,...,53.78,41.74,70.61,70.65,68.04,14.17,11.17,22.87,11.17,10.17
4,Aaron Hughes,1979-11-08,1.83,69.85,20.857595,73.24,74.68,right,45.08,38.84,...,46.48,52.96,77.60,76.04,74.60,8.28,8.32,24.92,12.84,11.92

# 4. Tratar valores faltantes

Veamos cuantos valores nulos tenemos

In [10]:
player_missing_values_count = player_df.isnull().sum()

player_missing_values_count[player_missing_values_count > 0]

volleys           478
curve             478
agility           478
balance           478
jumping           478
vision            478
sliding_tackle    478
dtype: int64

In [11]:
team_missing_values_count = team_df.isnull().sum()

team_missing_values_count[team_missing_values_count > 0]

Series([], dtype: int64)

In [12]:
match_missing_values_count = match_df.isnull().sum()

match_missing_values_count[match_missing_values_count > 0]

Series([], dtype: int64)

Algunas tecnicas para tratar los _missing values_:
* **Eliminar** muestras o variables que tienen datos faltantes.
* **Imputar** los valores perdidos, es decir, sustituirlos por estimaciones por ejemplo la `media`, la `moda` ó usando `KNN`.

A) Analizar si es conveniente **Eliminar** las muestras o variables con datos faltantes del Dataframe `player_df`. 

B) Aplicar la **Imputacion** usando la `media` o `moda` sobre las columnas con _missing values_ del Dataframe `player_df`.

**Hint**:
* Para la imputacion usando la `media`, `moda` ver el siguiente link:  
    https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html

### ¿Eliminar los _missing values_? Justificar

In [13]:
#registros NaN's...

player_df_NaNs = player_df[list(player_df.isnull().sum()[player_df.isnull().sum() > 0].index)][player_df.volleys.isnull()]
player_df_NaNs

       volleys  curve  agility  balance  jumping  vision  sliding_tackle
25         NaN    NaN      NaN      NaN      NaN     NaN             NaN
30         NaN    NaN      NaN      NaN      NaN     NaN             NaN
31         NaN    NaN      NaN      NaN      NaN     NaN             NaN
83         NaN    NaN      NaN      NaN      NaN     NaN             NaN
85         NaN    NaN      NaN      NaN      NaN     NaN             NaN
175        NaN    NaN      NaN      NaN      NaN     NaN             NaN
190        NaN    NaN      NaN      NaN      NaN     NaN             NaN
203        NaN    NaN      NaN      NaN      NaN     NaN             NaN
253        NaN    NaN      NaN      NaN      NaN     NaN             NaN
275        NaN    NaN      NaN      NaN      NaN     NaN             NaN
289        NaN    NaN      NaN      NaN      NaN     NaN             NaN
343        NaN    NaN      NaN      NaN      NaN     NaN             NaN
379        NaN    NaN      NaN      NaN      NaN     NaN             NaN
405        NaN    NaN      NaN      NaN      NaN     NaN             NaN
456        NaN    NaN      NaN      NaN      NaN     NaN             NaN
476        NaN    NaN      NaN      NaN      NaN     NaN             NaN
485        NaN    NaN      NaN      NaN      NaN     NaN             NaN
534        NaN    NaN      NaN      NaN      NaN     NaN             NaN
577        NaN    NaN      NaN      NaN      NaN     NaN             NaN
584        NaN    NaN      NaN      NaN      NaN     NaN             NaN
655        NaN    NaN      NaN      NaN      NaN     NaN             NaN
675        NaN    NaN      NaN      NaN      NaN     NaN             NaN
713        NaN    NaN      NaN      NaN      NaN     NaN             NaN
756        NaN    NaN      NaN      NaN      NaN     NaN             NaN
774        NaN    NaN      NaN      NaN      NaN     NaN             NaN
798        NaN    NaN      NaN      NaN      NaN     NaN             NaN
804        NaN    NaN      NaN      NaN      NaN     NaN             NaN
827        NaN    NaN      NaN      NaN      NaN     NaN             NaN
885        NaN    NaN      NaN      NaN      NaN     NaN             NaN
887        NaN    NaN      NaN      NaN      NaN     NaN             NaN
...        ...    ...      ...      ...      ...     ...             ...
10449      NaN    NaN      NaN      NaN      NaN     NaN             NaN
10475      NaN    NaN      NaN      NaN      NaN     NaN             NaN
10499      NaN    NaN      NaN      NaN      NaN     NaN             NaN
10504      NaN    NaN      NaN      NaN      NaN     NaN             NaN
10528      NaN    NaN      NaN      NaN      NaN     NaN             NaN
10545      NaN    NaN      NaN      NaN      NaN     NaN             NaN
10575      NaN    NaN      NaN      NaN      NaN     NaN             NaN
10627      NaN    NaN      NaN      NaN      NaN     NaN             NaN
10640      NaN    NaN      NaN      NaN      NaN     NaN             NaN
10670      NaN    NaN      NaN      NaN      NaN     NaN             NaN
10671      NaN    NaN      NaN      NaN      NaN     NaN             NaN
10674      NaN    NaN      NaN      NaN      NaN     NaN             NaN
10684      NaN    NaN      NaN      NaN      NaN     NaN             NaN
10692      NaN    NaN      NaN      NaN      NaN     NaN             NaN
10696      NaN    NaN      NaN      NaN      NaN     NaN             NaN
10711      NaN    NaN      NaN      NaN      NaN     NaN             NaN
10738      NaN    NaN      NaN      NaN      NaN     NaN             NaN
10742      NaN    NaN      NaN      NaN      NaN     NaN             NaN
10757      NaN    NaN      NaN      NaN      NaN     NaN             NaN
10802      NaN    NaN      NaN      NaN      NaN     NaN             NaN
10894      NaN    NaN      NaN      NaN      NaN     NaN             NaN
10909      NaN    NaN      NaN      NaN      NaN     NaN             NaN
10913      NaN    NaN      NaN      NaN      NaN     NaN             NaN
10924      NaN    NaN      NaN      NaN      NaN     NaN             NaN
10934      NaN    NaN      NaN      NaN      NaN     NaN             NaN
10949      NaN    NaN      NaN      NaN      NaN     NaN             NaN
10978      NaN    NaN      NaN      NaN      NaN     NaN             NaN
11020      NaN    NaN      NaN      NaN      NaN     NaN             NaN
11024      NaN    NaN      NaN      NaN      NaN     NaN             NaN
11027      NaN    NaN      NaN      NaN      NaN     NaN             NaN

[478 rows x 7 columns]

In [14]:
#porcentaje de registros NaN sobre player_df...

print('Porcentual de valores nulos sobre el universo player_df: {:.2f}%'.format(player_df_NaNs.shape[0] / player_df.shape[0] * 100))

Porcentual de valores nulos sobre el universo player_df: 4.32%

<h5><FONT COLOR="#FF0000"> La opción de eliminar los registros puede ser viable, representan menos del 5% del universo... aunque podríamos intentar una estrategia que evitara esto con K vecinos más cercanos.</FONT></h5>

### Imputacion usando Media y Moda

In [15]:
#estimamos media de las columnas NaN's...

player_df[player_df_NaNs.columns].mean()

volleys           47.110973
curve             50.423617
agility           64.409834
balance           64.475489
jumping           66.038396
vision            55.866959
sliding_tackle    47.124626
dtype: float64

In [16]:
#imputamos media a los valores NaN's...

player_df[player_df_NaNs.columns] = player_df[player_df_NaNs.columns].fillna(player_df[player_df_NaNs.columns].mean())

player_missing_values_count = player_df.isnull().sum()
player_missing_values_count[player_missing_values_count > 0]

Series([], dtype: int64)

# 5. Normalizacion de columnas

Primero que todo la notación:
* $x = [x_1, x_2, ..., x_n]$
* $\mu$: Media
* $\sigma$: Desviacion Estandar

Ahora normalizaremos algunas de las columnas del Dataframe, para ello usaremos dos tipos de normalizacion:

* Min-Max:  
$$
z_i = \frac{x_i - min(x)}{max(x) - min(x)}
$$
* Z-score
$$
z_i = \frac{x_i - \mu}{\sigma}
$$

Normalizar la columna `crossing` usando **Min-Max**.

Normalizar la columna `short_passing` usando **Z-score**.

**Hints**:
* https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html#sklearn.preprocessing.MinMaxScaler
* https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.zscore.html

### Min-Max

In [17]:
# TODO
from sklearn.preprocessing import MinMaxScaler

pre = player_df['crossing'].head().copy()
minmaxscaler = MinMaxScaler()
player_df['crossing'] = minmaxscaler.fit_transform(player_df['crossing'].values.reshape(-1, 1))
pos = player_df['crossing'].head().copy()

siamesas(pd.DataFrame(pre).rename(columns={'crossing': 'crossing(pre)'}), pd.DataFrame(pos).rename(columns={'crossing': 'crossing(pos)'}))

### Z-score

In [18]:
# TODO
from scipy import stats

pre = player_df['short_passing'].head().copy()
player_df['short_passing'] = stats.zscore(player_df['short_passing'])
pos = player_df['short_passing'].head().copy()

siamesas(pd.DataFrame(pre).rename(columns={'short_passing': 'short_passing(pre)'}), pd.DataFrame(pos).rename(columns={'short_passing': 'short_passing(pos)'}))

# 6. Codificar variables

> Las variables categóricas deben ser etiquetadas como variables numéricas, no como cadenas.

Codificar la variable `country_name` del Dataframe `match_df`

In [19]:
# TODO

match_df.country_name.value_counts()

England        3040
France         3040
Spain          3040
Italy          3017
Netherlands    2448
Germany        2448
Portugal       2052
Poland         1920
Scotland       1824
Belgium        1728
Switzerland    1422
Name: country_name, dtype: int64

More about preprocessing in:
* https://scikit-learn.org/stable/modules/classes.html#module-sklearn.preprocessing

In [20]:
#
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
xx = le.fit_transform(match_df['country_name'])

if 'country_name_le' in match_df.columns:
    match_df.drop('country_name_le', axis = 1, inplace = True)

match_df.insert(0, 'country_name_le', xx)

set(zip(le.classes_, le.transform(le.classes_)))

{('Belgium', 0),
 ('England', 1),
 ('France', 2),
 ('Germany', 3),
 ('Italy', 4),
 ('Netherlands', 5),
 ('Poland', 6),
 ('Portugal', 7),
 ('Scotland', 8),
 ('Spain', 9),
 ('Switzerland', 10)}

In [21]:
match_df

,country_name_le,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal
0,0,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-17,KRC Genk,GEN,Beerschot AC,BAC,1,1,2
1,0,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-16,SV Zulte-Waregem,ZUL,Sporting Lokeren,LOK,0,0,0
2,0,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-16,KSV Cercle Brugge,CEB,RSC Anderlecht,AND,0,3,3
3,0,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-17,KAA Gent,GEN,RAEC Mons,MON,5,0,5
4,0,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-16,FCV Dender EH,DEN,Standard de Liège,STL,1,3,4
5,0,Belgium,Belgium Jupiler League,2008/2009,1,2008-09-24,KV Mechelen,MEC,Club Brugge KV,CLB,1,1,2
6,0,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-16,KSV Roeselare,ROS,KV Kortrijk,KOR,2,2,4
7,0,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-16,Tubize,TUB,Royal Excel Mouscron,MOU,1,2,3
8,0,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-16,KVC Westerlo,WES,Sporting Charleroi,CHA,1,0,1
9,0,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-01,Club Brugge KV,CLB,KV Kortrijk,KOR,4,1,5
10,0,Belgium,Belgium Jupiler League,2008/2009,10,2008-10-31,Standard de Liège,STL,Sporting Charleroi,CHA,1,2,3
11,0,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-02,SV Zulte-Waregem,ZUL,KAA Gent,GEN,0,2,2
12,0,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-01,Sporting Lokeren,LOK,RAEC Mons,MON,0,0,0
13,0,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-01,FCV Dender EH,DEN,KVC Westerlo,WES,2,2,4
14,0,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-01,KV Mechelen,MEC,KSV Roeselare,ROS,1,2,3
15,0,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-01,Royal Excel Mouscron,MOU,KSV Cercle Brugge,CEB,0,1,1
16,0,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-01,Tubize,TUB,KRC Genk,GEN,1,3,4
17,0,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-02,Beerschot AC,BAC,RSC Anderlecht,AND,1,3,4
18,0,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-08,RSC Anderlecht,AND,Sporting Lokeren,LOK,2,3,5
19,0,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-08,RAEC Mons,MON,Royal Excel Mouscron,MOU,0,0,0
20,0,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-09,Sporting Charleroi,CHA,Club Brugge KV,CLB,2,2,4
21,0,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-07,KSV Cercle Brugge,CEB,SV Zulte-Waregem,ZUL,2,0,2
22,0,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-08,KAA Gent,GEN,FCV Dender EH,DEN,1,1,2
23,0,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-08,KSV Roeselare,ROS,Tubize,TUB,1,2,3
24,0,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-08,KV Kortrijk,KOR,KV Mechelen,MEC,0,0,0
25,0,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-08,KVC Westerlo,WES,KRC Genk,GEN,1,0,1
26,0,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-09,Beerschot AC,BAC,Standard de Liège,STL,1,3,4
27,0,Belgium,Belgium Jupiler League,2008/2009,12,2008-11-16,Club Brugge KV,CLB,RSC Anderlecht,AND,1,1,2
28,0,Belgium,Belgium Jupiler League,2008/2009,12,2008-11-15,KRC Genk,GEN,KSV Roeselare,ROS,1,1,2
29,0,Belgium,Belgium Jupiler League,2008/2009,12,2008-11-15,SV Zulte-Waregem,ZUL,Beerschot AC,BAC,2,2,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25949,10,Switzerland,Switzerland Super League,2015/2016,4,2015-08-08,Grasshopper Club Zürich,GRA,Lugano,LUG,6,1,7
25950,10,Switzerland,Switzerland Super League,2015/2016,4,2015-08-08,FC Luzern,LUZ,FC Basel,BAS,1,3,4
25951,10,Switzerland,Switzerland Super League,2015/2016,4,2015-08-09,FC St. Gallen,GAL,FC Zürich,ZUR,0,2,2
25952,10,Switzerland,Switzerland Super League,2015/2016,4,2015-08-09,FC Vaduz,VAD,FC Sion,SIO,1,1,2
25953,10,Switzerland,Switzerland Super League,2015/2016,4,2015-08-09,BSC Young Boys,YB,FC Thun,THU,3,1,4
25954,10,Switzerland,Switzerland Super League,2015/2016,5,2015-08-12,FC Basel,BAS,FC Thun,THU,3,1,4
25955,10,Switzerland,Switzerland Super League,2015/2016,5,2015-08-12,BSC Young Boys,YB,Lugano,LUG,0,1,1
25956,10,Switzerland,Switzerland Super League,2015/2016,5,2015-08-12,FC Luzern,LUZ,FC St. Gallen,GAL,0,1,1
25957,10,Switzerland,Switzerland Super League,2015/2016,5,2015-08-13,FC Sion,SIO,FC Zürich,ZUR,3,1,4
25958,10,Switzerland,Switzerland Super League,2015/2016,5,2015-08-13,FC Vaduz,VAD,Grasshopper Club Zürich,GRA,3,3,6
25959,10,Switzerland,Switzerland Super League,2015/2016,6,2015-08-22,Lugano,LUG,FC Basel,BAS,1,3,4
25960,10,Switzerland,Switzerland Super League,2015/2016,6,2015-08-23,FC Sion,SIO,BSC Young Boys,YB,1,3,4
25961,10,Switzerland,Switzerland Super League,2015/2016,6,2015-08-23,FC St. Gallen,GAL,Grasshopper Club Zürich,GRA,0,2,2
25962,10,Switzerland,Switzerland Super League,2015/2016,6,2015-08-23,FC Thun,THU,FC Vaduz,VAD,1,0,1
25963,10,Switzerland,Switzerland Super League,2015/2016,6,2015-08-22,FC Zürich,ZUR,FC Luzern,LUZ,2,5,7
25964,10,Switzerland,Switzerland Super League,2015/2016,7,2015-08-29,Lugano,LUG,FC Luzern,LUZ,0,1,1
25965,10,Switzerland,Switzerland Super League,2015/2016,7,2015-08-29,FC Vaduz,VAD,FC St. Gallen,GAL,1,0,1
25966,10,Switzerland,Switzerland Super League,2015/2016,7,2015-08-30,FC Thun,THU,FC Sion,SIO,0,2,2
25967,10,Switzerland,Switzerland Super League,2015/2016,7,2015-08-30,FC Basel,BAS,FC Zürich,ZUR,3,1,4
25968,10,Switzerland,Switzerland Super League,2015/2016,7,2015-08-30,Grasshopper Club Zürich,GRA,BSC Young Boys,YB,3,2,5
25969,10,Switzerland,Switzerland Super League,2015/2016,8,2015-09-12,FC Basel,BAS,FC St. Gallen,GAL,2,1,3
25970,10,Switzerland,Switzerland Super League,2015/2016,8,2015-09-12,BSC Young Boys,YB,FC Vaduz,VAD,4,0,4
25971,10,Switzerland,Switzerland Super League,2015/2016,8,2015-09-13,FC Luzern,LUZ,Grasshopper Club Zürich,GRA,3,3,6
25972,10,Switzerland,Switzerland Super League,2015/2016,8,2015-09-13,FC Zürich,ZUR,FC Thun,THU,3,3,6
25973,10,Switzerland,Switzerland Super League,2015/2016,8,2015-09-13,FC Sion,SIO,Lugano,LUG,3,0,3
25974,10,Switzerland,Switzerland Super League,2015/2016,9,2015-09-22,FC St. Gallen,GAL,FC Thun,THU,1,0,1
25975,10,Switzerland,Switzerland Super League,2015/2016,9,2015-09-23,FC Vaduz,VAD,FC Luzern,LUZ,1,2,3
25976,10,Switzerland,Switzerland Super League,2015/2016,9,2015-09-23,Grasshopper Club Zürich,GRA,FC Sion,SIO,2,0,2
25977,10,Switzerland,Switzerland Super League,2015/2016,9,2015-09-22,Lugano,LUG,FC Zürich,ZUR,0,0,0
25978,10,Switzerland,Switzerland Super League,2015/2016,9,2015-09-23,BSC Young Boys,YB,FC Basel,BAS,4,3,7