# Practico Mentoria - Analisis Exploratorio y Curación de Datos
<h3><FONT COLOR="#FF0000"> Alumno: Flavio Olivier (Omega)</FONT></h3>

---

### Importaciones

In [1]:
#paquetería...

%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy as sp

from sklearn import preprocessing

import warnings
warnings.filterwarnings('ignore')

In [2]:
# Set seed for reproducibility
np.random.seed(0)

In [3]:
#daterio...

path = 'https://raw.githubusercontent.com/diplodatos2019mentoria/Analisis_Visualizacion_Datos/master/'

player_df = pd.read_csv(path + 'Datasets/football_player.csv')
team_df = pd.read_csv(path + 'Datasets/football_team.csv')
match_df = pd.read_csv(path + 'Datasets/football_match.csv')

print("Shape 'player_df' = {}".format(player_df.shape))
print("Shape 'team_df'   = {}".format(team_df.shape))
print("Shape 'match_df'  = {}".format(match_df.shape))

Shape 'player_df' = (9925, 44)
Shape 'team_df'   = (288, 22)
Shape 'match_df'  = (25979, 15)

---

# 1. Importacion de los datos

Calculemos el rango de fechas de los partidos

In [4]:
match_df['date'].max() - match_df['date'].min()

TypeError: unsupported operand type(s) for -: 'str' and 'str'

Indiquemos que la columna `date` es una fechas como indica la [documentación](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#datetime-handling)

In [5]:
# TODO

match_df = pd.read_csv(path + 'Datasets/football_match.csv', parse_dates = ['date'])
match_df['date'].max() - match_df['date'].min()

Timedelta('2868 days 00:00:00')

# 2. Etiquetas de variables/columnas: no usar caracteres especiales

Chequar que no haya caracteres fuera de `a-Z`, `0-9` y `_` en los nombres de columnas de los Dataframes:
* `player_df`
* `team_df`
* `match_df`

In [6]:
# TODO

#caracteres especiales...
import re

def check(col):
    regex = re.match(r'([a-zA-Z0-9_])+$', col)
     
    if regex == None:
        validacion = 'INVALIDO'
    else:
        validacion = 'ok'
    
    return validacion

#side by side...
from IPython.display import display_html

def siamesas(*args):
    html_str = ''
    spaciador = '<table style="min-width: 40px !important;"><tr style="min-width: 40px !important; background:none !important;"><td style="min-width: 40px !important;"></td></tr></table>'
    for df in args:
        html_str += df.to_html() + spaciador
        
    display_html(html_str.replace('table', 'table style = "display:inline"'), raw = True)

In [7]:
#validamos nombres de columnas...

dfs = []
cols = []
estados = []

for df in ['player_df', 'team_df', 'match_df']:
    for col in pd.eval(df + '.columns'):
        #print(df, col, '->', check(col))
        dfs.append(df)
        cols.append(col)
        estados.append(check(col))

dfs = pd.DataFrame.from_dict({'tabla':dfs, 'columna':cols, 'valida':estados})
siamesas(dfs.loc[dfs.tabla == 'player_df'], dfs.loc[dfs.tabla == 'team_df'], dfs.loc[dfs.tabla == 'match_df'])

# 3. Agregar nuevas caracteristicas

Agregar al Dataframe `player_df` una nueva columna que sea `imc` correspondiente al **Indice de Masa Corporal**

Link:
* https://www.texasheart.org/heart-health/heart-information-center/topics/calculadora-del-indice-de-masa-corporal-imc/

In [8]:
# TODO

player_df.insert(5, 'IMC', player_df['weight_kg'] / player_df['height_m']**2)
player_df.head()

,player_name,birthday,age,height_m,weight_kg,IMC,imc,overall_rating,potential,preferred_foot,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,Aaron Appindangoye,1992-02-29,24,1.83,84.82,25.327720,25.36,63.60,67.60,right,...,53.60,47.60,63.80,66.00,67.80,5.60,10.60,9.60,7.60,7.60
1,Aaron Cresswell,1989-12-15,26,1.70,66.22,22.913495,22.87,66.97,74.48,left,...,57.45,53.12,69.39,68.79,71.52,12.18,8.67,14.24,10.36,12.91
2,Aaron Doran,1991-05-13,25,1.70,73.94,25.584775,25.53,67.00,74.19,right,...,69.38,60.54,22.04,21.12,21.35,14.04,11.81,17.73,10.12,13.50
3,Aaron Galindo,1982-05-08,34,1.83,89.81,26.817761,26.85,69.09,70.78,right,...,53.78,41.74,70.61,70.65,68.04,14.17,11.17,22.87,11.17,10.17
4,Aaron Hughes,1979-11-08,36,1.83,69.85,20.857595,20.89,73.24,74.68,right,...,46.48,52.96,77.60,76.04,74.60,8.28,8.32,24.92,12.84,11.92

# 4. Tratar valores faltantes

Veamos cuantos valores nulos tenemos

In [9]:
player_missing_values_count = player_df.isnull().sum()

player_missing_values_count[player_missing_values_count > 0]

Series([], dtype: int64)

In [10]:
team_missing_values_count = team_df.isnull().sum()

team_missing_values_count[team_missing_values_count > 0]

Series([], dtype: int64)

In [11]:
match_missing_values_count = match_df.isnull().sum()

match_missing_values_count[match_missing_values_count > 0]

B365H    3387
B365D    3387
B365A    3387
dtype: int64

Algunas tecnicas para tratar los _missing values_:
* **Eliminar** muestras o variables que tienen datos faltantes.
* **Imputar** los valores perdidos, es decir, sustituirlos por estimaciones por ejemplo la `media`, la `moda` ó usando `KNN`.

A) Analizar si es conveniente **Eliminar** las muestras o variables con datos faltantes del Dataframe `player_df`. 

B) Aplicar la **Imputacion** usando la `media` o `moda` sobre las columnas con _missing values_ del Dataframe `player_df`.

**Hint**:
* Para la imputacion usando la `media`, `moda` ver el siguiente link:  
    https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html

<h4><FONT COLOR="#FF0000">¡Atención!, no encuentro datos faltantes en player_df: opero sobre match_df</FONT></h4>

### ¿Eliminar los _missing values_? Justificar

In [12]:
# TODO

#B365H: Bet365 Home win odds
#B365D: Bet365 Draw odds
#B365A: Bet365 Away win odds

#contamos y ordenamos NaN's por ligas...
#... lo contratasmos con la cantidad de juegos por liga.

match_nan = match_df['B365H'].isnull().groupby(match_df['league_name']).agg({'NaN':sum}).sort_values('league_name', ascending = False).reset_index()
match_count = match_df.groupby(match_df['league_name']).agg({'stage':'count'}).sort_values('league_name', ascending = False).reset_index().rename(columns={'stage': 'cuantos'})

siamesas(match_nan, match_count)

<h4><FONT COLOR="#FF0000">'Switzerland Super League' y 'Poland Ekstraklasa' tienen la totalidad de sus registros como NaN</FONT></h4>

In [13]:
#tomamos como ejemplo el NaN de 'Spain LIGA BBVA'...

match_df.loc[(match_df['league_name'] == 'Spain LIGA BBVA') & (match_df['B365H'].isnull())]

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
21630,Spain,Spain LIGA BBVA,2008/2009,2,2008-09-13,Sevilla FC,SEV,Real Sporting de Gijón,SPG,4,3,7,NaN,NaN,NaN

In [14]:
#listamos todos los juegos que tengan al 'Sevilla FC' como local y a 'Real Sporting de Gijón' como visitante...

match_df.loc[(match_df['home_team_long_name'] == 'Sevilla FC') & (match_df['away_team_long_name'] == 'Real Sporting de Gijón')]

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
21630,Spain,Spain LIGA BBVA,2008/2009,2,2008-09-13,Sevilla FC,SEV,Real Sporting de Gijón,SPG,4,3,7,NaN,NaN,NaN
22158,Spain,Spain LIGA BBVA,2009/2010,33,2010-04-17,Sevilla FC,SEV,Real Sporting de Gijón,SPG,3,0,3,1.40,4.33,8.5
22459,Spain,Spain LIGA BBVA,2010/2011,26,2011-03-01,Sevilla FC,SEV,Real Sporting de Gijón,SPG,3,0,3,1.57,4.00,5.5
23024,Spain,Spain LIGA BBVA,2011/2012,8,2011-10-16,Sevilla FC,SEV,Real Sporting de Gijón,SPG,2,1,3,1.36,4.75,8.5
24241,Spain,Spain LIGA BBVA,2015/2016,15,2015-12-12,Sevilla FC,SEV,Real Sporting de Gijón,SPG,2,0,2,1.36,5.00,8.5

<h4><FONT COLOR="#FF0000">Tal vez la opción de agrupar/filtrar los juegos que tienen los mismos equipos como local vs visitante y promediar sus valores para utilizarlos como reemplazo de los NaN podría funcionar mejor que eliminar registros.</FONT></h4>

### Imputacion usando Media y Moda

In [15]:
#aplicamos esto al ejemplo anterior: Sevilla FC vs Real Sporting de Gijón...

match_df.loc[(match_df['home_team_long_name'] == 'Sevilla FC') & (match_df['away_team_long_name'] == 'Real Sporting de Gijón')].fillna(match_df.loc[(match_df['home_team_long_name'] == 'Sevilla FC') & (match_df['away_team_long_name'] == 'Real Sporting de Gijón')].mean())

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
21630,Spain,Spain LIGA BBVA,2008/2009,2,2008-09-13,Sevilla FC,SEV,Real Sporting de Gijón,SPG,4,3,7,1.4225,4.52,7.75
22158,Spain,Spain LIGA BBVA,2009/2010,33,2010-04-17,Sevilla FC,SEV,Real Sporting de Gijón,SPG,3,0,3,1.4000,4.33,8.50
22459,Spain,Spain LIGA BBVA,2010/2011,26,2011-03-01,Sevilla FC,SEV,Real Sporting de Gijón,SPG,3,0,3,1.5700,4.00,5.50
23024,Spain,Spain LIGA BBVA,2011/2012,8,2011-10-16,Sevilla FC,SEV,Real Sporting de Gijón,SPG,2,1,3,1.3600,4.75,8.50
24241,Spain,Spain LIGA BBVA,2015/2016,15,2015-12-12,Sevilla FC,SEV,Real Sporting de Gijón,SPG,2,0,2,1.3600,5.00,8.50

In [16]:
# y ahora intentamos generalizarlo a todas las ligas menos 'Switzerland Super League' y 'Poland Ekstraklasa...

NaNs = match_df['B365H'].isnull().groupby(match_df['league_name']).agg({'NaN':sum}).sort_values('NaN', ascending = True).reset_index()
NaNs = NaNs.loc[NaNs.NaN > 0]
NaNs

                 league_name     NaN
2      Germany 1. Bundesliga     1.0
3            Spain LIGA BBVA     1.0
4     Netherlands Eredivisie     3.0
5             France Ligue 1     4.0
6              Italy Serie A     6.0
7   Portugal Liga ZON Sagres     8.0
8     Belgium Jupiler League    22.0
9   Switzerland Super League  1422.0
10        Poland Ekstraklasa  1920.0

In [17]:
#ejecutamos sobre todas las ligas menos 'Switzerland Super League' y 'Poland Ekstraklasa...

for i, r in NaNs.iterrows():
    #print(i, r['league_name'])
    display(match_df.loc[(match_df['league_name'] == r['league_name']) & (match_df['B365H'].isnull())])
    
    juegos_nan = match_df.loc[(match_df['league_name'] == r['league_name']) & (match_df['B365H'].isnull())]
    
    c = 0
    for i1, r1 in juegos_nan.iterrows():
        local_nan = juegos_nan.iloc[c].home_team_long_name
        visita_nan = juegos_nan.iloc[c].away_team_long_name
        display(match_df.loc[(match_df['home_team_long_name'] == local_nan) & (match_df['away_team_long_name'] == visita_nan)])
        display(match_df.loc[(match_df['home_team_long_name'] == local_nan) & (match_df['away_team_long_name'] == visita_nan)].fillna(match_df.loc[(match_df['home_team_long_name'] == local_nan) & (match_df['away_team_long_name'] == visita_nan)].mean()))
        c = c + 1
        idx = match_df.loc[(match_df['home_team_long_name'] == local_nan) & (match_df['away_team_long_name'] == visita_nan)].index
        d = match_df.loc[idx, ['B365H', 'B365D', 'B365A']].mean().to_dict()
        match_df.loc[idx, ['B365H', 'B365D', 'B365A']] = match_df.loc[idx, ['B365H', 'B365D', 'B365A']].fillna(d)
    
    if i > 7:
        break

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
9034,Germany,Germany 1. Bundesliga,2012/2013,1,2012-08-25,VfB Stuttgart,STU,VfL Wolfsburg,WOL,0,1,1,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
8026,Germany,Germany 1. Bundesliga,2008/2009,31,2009-05-09,VfB Stuttgart,STU,VfL Wolfsburg,WOL,4,1,5,2.20,3.40,3.20
8198,Germany,Germany 1. Bundesliga,2009/2010,18,2010-01-16,VfB Stuttgart,STU,VfL Wolfsburg,WOL,3,1,4,2.25,3.25,3.20
8593,Germany,Germany 1. Bundesliga,2010/2011,27,2011-03-20,VfB Stuttgart,STU,VfL Wolfsburg,WOL,1,1,2,1.95,3.50,3.75
8974,Germany,Germany 1. Bundesliga,2011/2012,34,2012-05-05,VfB Stuttgart,STU,VfL Wolfsburg,WOL,3,2,5,1.91,3.75,3.60
9034,Germany,Germany 1. Bundesliga,2012/2013,1,2012-08-25,VfB Stuttgart,STU,VfL Wolfsburg,WOL,0,1,1,NaN,NaN,NaN
9574,Germany,Germany 1. Bundesliga,2013/2014,33,2014-05-03,VfB Stuttgart,STU,VfL Wolfsburg,WOL,1,2,3,2.70,3.60,2.40
9658,Germany,Germany 1. Bundesliga,2014/2015,10,2014-11-01,VfB Stuttgart,STU,VfL Wolfsburg,WOL,0,4,4,3.30,3.50,2.10
10025,Germany,Germany 1. Bundesliga,2015/2016,17,2015-12-19,VfB Stuttgart,STU,VfL Wolfsburg,WOL,3,1,4,3.50,3.60,2.00

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
8026,Germany,Germany 1. Bundesliga,2008/2009,31,2009-05-09,VfB Stuttgart,STU,VfL Wolfsburg,WOL,4,1,5,2.200000,3.400000,3.200000
8198,Germany,Germany 1. Bundesliga,2009/2010,18,2010-01-16,VfB Stuttgart,STU,VfL Wolfsburg,WOL,3,1,4,2.250000,3.250000,3.200000
8593,Germany,Germany 1. Bundesliga,2010/2011,27,2011-03-20,VfB Stuttgart,STU,VfL Wolfsburg,WOL,1,1,2,1.950000,3.500000,3.750000
8974,Germany,Germany 1. Bundesliga,2011/2012,34,2012-05-05,VfB Stuttgart,STU,VfL Wolfsburg,WOL,3,2,5,1.910000,3.750000,3.600000
9034,Germany,Germany 1. Bundesliga,2012/2013,1,2012-08-25,VfB Stuttgart,STU,VfL Wolfsburg,WOL,0,1,1,2.544286,3.514286,2.892857
9574,Germany,Germany 1. Bundesliga,2013/2014,33,2014-05-03,VfB Stuttgart,STU,VfL Wolfsburg,WOL,1,2,3,2.700000,3.600000,2.400000
9658,Germany,Germany 1. Bundesliga,2014/2015,10,2014-11-01,VfB Stuttgart,STU,VfL Wolfsburg,WOL,0,4,4,3.300000,3.500000,2.100000
10025,Germany,Germany 1. Bundesliga,2015/2016,17,2015-12-19,VfB Stuttgart,STU,VfL Wolfsburg,WOL,3,1,4,3.500000,3.600000,2.000000

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
21630,Spain,Spain LIGA BBVA,2008/2009,2,2008-09-13,Sevilla FC,SEV,Real Sporting de Gijón,SPG,4,3,7,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
21630,Spain,Spain LIGA BBVA,2008/2009,2,2008-09-13,Sevilla FC,SEV,Real Sporting de Gijón,SPG,4,3,7,NaN,NaN,NaN
22158,Spain,Spain LIGA BBVA,2009/2010,33,2010-04-17,Sevilla FC,SEV,Real Sporting de Gijón,SPG,3,0,3,1.40,4.33,8.5
22459,Spain,Spain LIGA BBVA,2010/2011,26,2011-03-01,Sevilla FC,SEV,Real Sporting de Gijón,SPG,3,0,3,1.57,4.00,5.5
23024,Spain,Spain LIGA BBVA,2011/2012,8,2011-10-16,Sevilla FC,SEV,Real Sporting de Gijón,SPG,2,1,3,1.36,4.75,8.5
24241,Spain,Spain LIGA BBVA,2015/2016,15,2015-12-12,Sevilla FC,SEV,Real Sporting de Gijón,SPG,2,0,2,1.36,5.00,8.5

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
21630,Spain,Spain LIGA BBVA,2008/2009,2,2008-09-13,Sevilla FC,SEV,Real Sporting de Gijón,SPG,4,3,7,1.4225,4.52,7.75
22158,Spain,Spain LIGA BBVA,2009/2010,33,2010-04-17,Sevilla FC,SEV,Real Sporting de Gijón,SPG,3,0,3,1.4000,4.33,8.50
22459,Spain,Spain LIGA BBVA,2010/2011,26,2011-03-01,Sevilla FC,SEV,Real Sporting de Gijón,SPG,3,0,3,1.5700,4.00,5.50
23024,Spain,Spain LIGA BBVA,2011/2012,8,2011-10-16,Sevilla FC,SEV,Real Sporting de Gijón,SPG,2,1,3,1.3600,4.75,8.50
24241,Spain,Spain LIGA BBVA,2015/2016,15,2015-12-12,Sevilla FC,SEV,Real Sporting de Gijón,SPG,2,0,2,1.3600,5.00,8.50

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
13439,Netherlands,Netherlands Eredivisie,2008/2009,26,2009-03-08,FC Twente,TWE,PSV,PSV,1,1,2,NaN,NaN,NaN
13786,Netherlands,Netherlands Eredivisie,2009/2010,30,2010-04-03,Vitesse,VIT,FC Groningen,GRO,3,0,3,NaN,NaN,NaN
14698,Netherlands,Netherlands Eredivisie,2012/2013,3,2012-08-26,Heracles Almelo,HER,Feyenoord,FEY,1,2,3,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
13439,Netherlands,Netherlands Eredivisie,2008/2009,26,2009-03-08,FC Twente,TWE,PSV,PSV,1,1,2,NaN,NaN,NaN
13683,Netherlands,Netherlands Eredivisie,2009/2010,2,2009-08-09,FC Twente,TWE,PSV,PSV,1,1,2,2.55,3.25,2.55
14078,Netherlands,Netherlands Eredivisie,2010/2011,29,2011-04-02,FC Twente,TWE,PSV,PSV,2,0,2,2.30,3.25,3.10
14213,Netherlands,Netherlands Eredivisie,2011/2012,11,2011-10-29,FC Twente,TWE,PSV,PSV,2,2,4,2.40,3.40,2.80
14746,Netherlands,Netherlands Eredivisie,2012/2013,34,2013-05-12,FC Twente,TWE,PSV,PSV,3,1,4,2.75,3.50,2.25
15077,Netherlands,Netherlands Eredivisie,2013/2014,6,2013-09-14,FC Twente,TWE,PSV,PSV,2,2,4,2.40,3.50,2.80
15302,Netherlands,Netherlands Eredivisie,2014/2015,29,2015-04-04,FC Twente,TWE,PSV,PSV,0,5,5,3.60,3.60,1.95
15427,Netherlands,Netherlands Eredivisie,2015/2016,10,2015-10-24,FC Twente,TWE,PSV,PSV,1,3,4,4.20,4.00,1.73

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
13439,Netherlands,Netherlands Eredivisie,2008/2009,26,2009-03-08,FC Twente,TWE,PSV,PSV,1,1,2,2.885714,3.50,2.454286
13683,Netherlands,Netherlands Eredivisie,2009/2010,2,2009-08-09,FC Twente,TWE,PSV,PSV,1,1,2,2.550000,3.25,2.550000
14078,Netherlands,Netherlands Eredivisie,2010/2011,29,2011-04-02,FC Twente,TWE,PSV,PSV,2,0,2,2.300000,3.25,3.100000
14213,Netherlands,Netherlands Eredivisie,2011/2012,11,2011-10-29,FC Twente,TWE,PSV,PSV,2,2,4,2.400000,3.40,2.800000
14746,Netherlands,Netherlands Eredivisie,2012/2013,34,2013-05-12,FC Twente,TWE,PSV,PSV,3,1,4,2.750000,3.50,2.250000
15077,Netherlands,Netherlands Eredivisie,2013/2014,6,2013-09-14,FC Twente,TWE,PSV,PSV,2,2,4,2.400000,3.50,2.800000
15302,Netherlands,Netherlands Eredivisie,2014/2015,29,2015-04-04,FC Twente,TWE,PSV,PSV,0,5,5,3.600000,3.60,1.950000
15427,Netherlands,Netherlands Eredivisie,2015/2016,10,2015-10-24,FC Twente,TWE,PSV,PSV,1,3,4,4.200000,4.00,1.730000

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
13273,Netherlands,Netherlands Eredivisie,2008/2009,1,2008-08-29,Vitesse,VIT,FC Groningen,GRO,0,4,4,2.20,3.30,3.00
13786,Netherlands,Netherlands Eredivisie,2009/2010,30,2010-04-03,Vitesse,VIT,FC Groningen,GRO,3,0,3,NaN,NaN,NaN
14104,Netherlands,Netherlands Eredivisie,2010/2011,31,2011-04-16,Vitesse,VIT,FC Groningen,GRO,2,1,3,2.40,3.30,2.88
14262,Netherlands,Netherlands Eredivisie,2011/2012,16,2011-12-11,Vitesse,VIT,FC Groningen,GRO,0,0,0,2.10,3.40,3.40
14639,Netherlands,Netherlands Eredivisie,2012/2013,23,2013-02-17,Vitesse,VIT,FC Groningen,GRO,2,0,2,1.67,3.80,5.00
14829,Netherlands,Netherlands Eredivisie,2013/2014,11,2013-10-27,Vitesse,VIT,FC Groningen,GRO,2,2,4,1.73,4.00,4.20
15299,Netherlands,Netherlands Eredivisie,2014/2015,29,2015-04-04,Vitesse,VIT,FC Groningen,GRO,1,1,2,1.33,5.25,8.00
15710,Netherlands,Netherlands Eredivisie,2015/2016,8,2015-10-04,Vitesse,VIT,FC Groningen,GRO,5,0,5,1.53,4.33,5.50

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
13273,Netherlands,Netherlands Eredivisie,2008/2009,1,2008-08-29,Vitesse,VIT,FC Groningen,GRO,0,4,4,2.200000,3.300000,3.000000
13786,Netherlands,Netherlands Eredivisie,2009/2010,30,2010-04-03,Vitesse,VIT,FC Groningen,GRO,3,0,3,1.851429,3.911429,4.568571
14104,Netherlands,Netherlands Eredivisie,2010/2011,31,2011-04-16,Vitesse,VIT,FC Groningen,GRO,2,1,3,2.400000,3.300000,2.880000
14262,Netherlands,Netherlands Eredivisie,2011/2012,16,2011-12-11,Vitesse,VIT,FC Groningen,GRO,0,0,0,2.100000,3.400000,3.400000
14639,Netherlands,Netherlands Eredivisie,2012/2013,23,2013-02-17,Vitesse,VIT,FC Groningen,GRO,2,0,2,1.670000,3.800000,5.000000
14829,Netherlands,Netherlands Eredivisie,2013/2014,11,2013-10-27,Vitesse,VIT,FC Groningen,GRO,2,2,4,1.730000,4.000000,4.200000
15299,Netherlands,Netherlands Eredivisie,2014/2015,29,2015-04-04,Vitesse,VIT,FC Groningen,GRO,1,1,2,1.330000,5.250000,8.000000
15710,Netherlands,Netherlands Eredivisie,2015/2016,8,2015-10-04,Vitesse,VIT,FC Groningen,GRO,5,0,5,1.530000,4.330000,5.500000

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
13278,Netherlands,Netherlands Eredivisie,2008/2009,1,2008-08-31,Heracles Almelo,HER,Feyenoord,FEY,3,1,4,4.33,3.25,1.80
13785,Netherlands,Netherlands Eredivisie,2009/2010,3,2009-08-16,Heracles Almelo,HER,Feyenoord,FEY,0,1,1,3.40,3.30,2.15
14089,Netherlands,Netherlands Eredivisie,2010/2011,3,2010-08-22,Heracles Almelo,HER,Feyenoord,FEY,1,1,2,2.75,3.30,2.50
14394,Netherlands,Netherlands Eredivisie,2011/2012,3,2011-08-21,Heracles Almelo,HER,Feyenoord,FEY,1,1,2,2.00,3.60,3.50
14698,Netherlands,Netherlands Eredivisie,2012/2013,3,2012-08-26,Heracles Almelo,HER,Feyenoord,FEY,1,2,3,NaN,NaN,NaN
14999,Netherlands,Netherlands Eredivisie,2013/2014,29,2014-04-02,Heracles Almelo,HER,Feyenoord,FEY,1,2,3,4.20,4.00,1.73
15245,Netherlands,Netherlands Eredivisie,2014/2015,23,2015-02-14,Heracles Almelo,HER,Feyenoord,FEY,2,0,2,5.50,4.00,1.57
15648,Netherlands,Netherlands Eredivisie,2015/2016,32,2016-04-20,Heracles Almelo,HER,Feyenoord,FEY,2,2,4,4.00,3.75,1.83

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
13278,Netherlands,Netherlands Eredivisie,2008/2009,1,2008-08-31,Heracles Almelo,HER,Feyenoord,FEY,3,1,4,4.33,3.25,1.800000
13785,Netherlands,Netherlands Eredivisie,2009/2010,3,2009-08-16,Heracles Almelo,HER,Feyenoord,FEY,0,1,1,3.40,3.30,2.150000
14089,Netherlands,Netherlands Eredivisie,2010/2011,3,2010-08-22,Heracles Almelo,HER,Feyenoord,FEY,1,1,2,2.75,3.30,2.500000
14394,Netherlands,Netherlands Eredivisie,2011/2012,3,2011-08-21,Heracles Almelo,HER,Feyenoord,FEY,1,1,2,2.00,3.60,3.500000
14698,Netherlands,Netherlands Eredivisie,2012/2013,3,2012-08-26,Heracles Almelo,HER,Feyenoord,FEY,1,2,3,3.74,3.60,2.154286
14999,Netherlands,Netherlands Eredivisie,2013/2014,29,2014-04-02,Heracles Almelo,HER,Feyenoord,FEY,1,2,3,4.20,4.00,1.730000
15245,Netherlands,Netherlands Eredivisie,2014/2015,23,2015-02-14,Heracles Almelo,HER,Feyenoord,FEY,2,0,2,5.50,4.00,1.570000
15648,Netherlands,Netherlands Eredivisie,2015/2016,32,2016-04-20,Heracles Almelo,HER,Feyenoord,FEY,2,2,4,4.00,3.75,1.830000

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
4857,France,France Ligue 1,2008/2009,17,2008-12-06,FC Nantes,NAN,Olympique Lyonnais,LYO,2,1,3,NaN,NaN,NaN
5381,France,France Ligue 1,2009/2010,30,2010-03-27,Olympique Lyonnais,LYO,Grenoble Foot 38,GRE,2,0,2,NaN,NaN,NaN
5600,France,France Ligue 1,2010/2011,16,2010-12-05,LOSC Lille,LIL,FC Lorient,LOR,6,3,9,NaN,NaN,NaN
7715,France,France Ligue 1,2015/2016,35,2016-04-24,Olympique de Marseille,MAR,FC Nantes,NAN,1,1,2,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
4857,France,France Ligue 1,2008/2009,17,2008-12-06,FC Nantes,NAN,Olympique Lyonnais,LYO,2,1,3,NaN,NaN,NaN
6830,France,France Ligue 1,2013/2014,24,2014-02-09,FC Nantes,NAN,Olympique Lyonnais,LYO,1,2,3,3.00,3.00,2.50
7416,France,France Ligue 1,2014/2015,8,2014-09-28,FC Nantes,NAN,Olympique Lyonnais,LYO,1,1,2,2.75,3.10,2.63
7505,France,France Ligue 1,2015/2016,16,2015-12-01,FC Nantes,NAN,Olympique Lyonnais,LYO,0,0,0,3.60,3.25,2.15

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
4857,France,France Ligue 1,2008/2009,17,2008-12-06,FC Nantes,NAN,Olympique Lyonnais,LYO,2,1,3,3.116667,3.116667,2.426667
6830,France,France Ligue 1,2013/2014,24,2014-02-09,FC Nantes,NAN,Olympique Lyonnais,LYO,1,2,3,3.000000,3.000000,2.500000
7416,France,France Ligue 1,2014/2015,8,2014-09-28,FC Nantes,NAN,Olympique Lyonnais,LYO,1,1,2,2.750000,3.100000,2.630000
7505,France,France Ligue 1,2015/2016,16,2015-12-01,FC Nantes,NAN,Olympique Lyonnais,LYO,0,0,0,3.600000,3.250000,2.150000

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
4992,France,France Ligue 1,2008/2009,3,2008-08-23,Olympique Lyonnais,LYO,Grenoble Foot 38,GRE,2,0,2,1.29,4.75,13.0
5381,France,France Ligue 1,2009/2010,30,2010-03-27,Olympique Lyonnais,LYO,Grenoble Foot 38,GRE,2,0,2,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
4992,France,France Ligue 1,2008/2009,3,2008-08-23,Olympique Lyonnais,LYO,Grenoble Foot 38,GRE,2,0,2,1.29,4.75,13.0
5381,France,France Ligue 1,2009/2010,30,2010-03-27,Olympique Lyonnais,LYO,Grenoble Foot 38,GRE,2,0,2,1.29,4.75,13.0

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
4841,France,France Ligue 1,2008/2009,16,2008-11-29,LOSC Lille,LIL,FC Lorient,LOR,1,1,2,1.57,3.6,6.50
5152,France,France Ligue 1,2009/2010,1,2009-08-09,LOSC Lille,LIL,FC Lorient,LOR,1,2,3,1.67,3.3,5.50
5600,France,France Ligue 1,2010/2011,16,2010-12-05,LOSC Lille,LIL,FC Lorient,LOR,6,3,9,NaN,NaN,NaN
6271,France,France Ligue 1,2011/2012,8,2011-09-24,LOSC Lille,LIL,FC Lorient,LOR,1,1,2,1.57,3.6,6.50
6529,France,France Ligue 1,2012/2013,31,2013-04-07,LOSC Lille,LIL,FC Lorient,LOR,5,0,5,1.67,3.5,5.50
6672,France,France Ligue 1,2013/2014,1,2013-08-10,LOSC Lille,LIL,FC Lorient,LOR,1,0,1,1.62,3.6,6.00
7271,France,France Ligue 1,2014/2015,3,2014-08-23,LOSC Lille,LIL,FC Lorient,LOR,2,0,2,1.75,3.4,5.00
7519,France,France Ligue 1,2015/2016,18,2015-12-12,LOSC Lille,LIL,FC Lorient,LOR,3,0,3,1.75,3.5,5.25

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
4841,France,France Ligue 1,2008/2009,16,2008-11-29,LOSC Lille,LIL,FC Lorient,LOR,1,1,2,1.570000,3.6,6.50
5152,France,France Ligue 1,2009/2010,1,2009-08-09,LOSC Lille,LIL,FC Lorient,LOR,1,2,3,1.670000,3.3,5.50
5600,France,France Ligue 1,2010/2011,16,2010-12-05,LOSC Lille,LIL,FC Lorient,LOR,6,3,9,1.657143,3.5,5.75
6271,France,France Ligue 1,2011/2012,8,2011-09-24,LOSC Lille,LIL,FC Lorient,LOR,1,1,2,1.570000,3.6,6.50
6529,France,France Ligue 1,2012/2013,31,2013-04-07,LOSC Lille,LIL,FC Lorient,LOR,5,0,5,1.670000,3.5,5.50
6672,France,France Ligue 1,2013/2014,1,2013-08-10,LOSC Lille,LIL,FC Lorient,LOR,1,0,1,1.620000,3.6,6.00
7271,France,France Ligue 1,2014/2015,3,2014-08-23,LOSC Lille,LIL,FC Lorient,LOR,2,0,2,1.750000,3.4,5.00
7519,France,France Ligue 1,2015/2016,18,2015-12-12,LOSC Lille,LIL,FC Lorient,LOR,3,0,3,1.750000,3.5,5.25

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
4983,France,France Ligue 1,2008/2009,29,2009-03-21,Olympique de Marseille,MAR,FC Nantes,NAN,2,0,2,1.45,3.75,8.0
6751,France,France Ligue 1,2013/2014,17,2013-12-06,Olympique de Marseille,MAR,FC Nantes,NAN,0,1,1,1.85,3.30,4.5
7112,France,France Ligue 1,2014/2015,15,2014-11-28,Olympique de Marseille,MAR,FC Nantes,NAN,2,0,2,1.53,3.75,7.5
7715,France,France Ligue 1,2015/2016,35,2016-04-24,Olympique de Marseille,MAR,FC Nantes,NAN,1,1,2,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
4983,France,France Ligue 1,2008/2009,29,2009-03-21,Olympique de Marseille,MAR,FC Nantes,NAN,2,0,2,1.45,3.75,8.000000
6751,France,France Ligue 1,2013/2014,17,2013-12-06,Olympique de Marseille,MAR,FC Nantes,NAN,0,1,1,1.85,3.30,4.500000
7112,France,France Ligue 1,2014/2015,15,2014-11-28,Olympique de Marseille,MAR,FC Nantes,NAN,2,0,2,1.53,3.75,7.500000
7715,France,France Ligue 1,2015/2016,35,2016-04-24,Olympique de Marseille,MAR,FC Nantes,NAN,1,1,2,1.61,3.60,6.666667

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
10939,Italy,Italy Serie A,2009/2010,37,2010-05-09,Bologna,BOL,Catania,CAT,1,1,2,NaN,NaN,NaN
11146,Italy,Italy Serie A,2010/2011,21,2011-01-23,Chievo Verona,CHI,Genoa,GEN,0,0,0,NaN,NaN,NaN
11278,Italy,Italy Serie A,2010/2011,33,2011-04-17,Genoa,GEN,Brescia,BRE,3,0,3,NaN,NaN,NaN
11281,Italy,Italy Serie A,2010/2011,33,2011-04-17,Chievo Verona,CHI,Bologna,BOL,2,0,2,NaN,NaN,NaN
11539,Italy,Italy Serie A,2011/2012,22,2012-02-05,Roma,ROM,Inter,INT,4,0,4,NaN,NaN,NaN
11884,Italy,Italy Serie A,2012/2013,21,2013-01-20,Milan,ACM,Bologna,BOL,2,1,3,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
10571,Italy,Italy Serie A,2008/2009,38,2009-05-31,Bologna,BOL,Catania,CAT,3,1,4,1.3,4.75,12.0
10939,Italy,Italy Serie A,2009/2010,37,2010-05-09,Bologna,BOL,Catania,CAT,1,1,2,NaN,NaN,NaN
11180,Italy,Italy Serie A,2010/2011,24,2011-02-06,Bologna,BOL,Catania,CAT,1,0,1,2.1,3.25,3.5
11477,Italy,Italy Serie A,2011/2012,17,2012-01-08,Bologna,BOL,Catania,CAT,2,0,2,2.3,3.20,3.2
12095,Italy,Italy Serie A,2012/2013,6,2012-09-30,Bologna,BOL,Catania,CAT,4,0,4,2.4,3.30,2.9
12434,Italy,Italy Serie A,2013/2014,37,2014-05-11,Bologna,BOL,Catania,CAT,1,2,3,2.0,3.50,3.6

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
10571,Italy,Italy Serie A,2008/2009,38,2009-05-31,Bologna,BOL,Catania,CAT,3,1,4,1.30,4.75,12.00
10939,Italy,Italy Serie A,2009/2010,37,2010-05-09,Bologna,BOL,Catania,CAT,1,1,2,2.02,3.60,5.04
11180,Italy,Italy Serie A,2010/2011,24,2011-02-06,Bologna,BOL,Catania,CAT,1,0,1,2.10,3.25,3.50
11477,Italy,Italy Serie A,2011/2012,17,2012-01-08,Bologna,BOL,Catania,CAT,2,0,2,2.30,3.20,3.20
12095,Italy,Italy Serie A,2012/2013,6,2012-09-30,Bologna,BOL,Catania,CAT,4,0,4,2.40,3.30,2.90
12434,Italy,Italy Serie A,2013/2014,37,2014-05-11,Bologna,BOL,Catania,CAT,1,2,3,2.00,3.50,3.60

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
10343,Italy,Italy Serie A,2008/2009,17,2008-12-21,Chievo Verona,CHI,Genoa,GEN,0,1,1,2.50,3.0,3.0
10959,Italy,Italy Serie A,2009/2010,4,2009-09-20,Chievo Verona,CHI,Genoa,GEN,3,1,4,2.90,3.1,2.5
11146,Italy,Italy Serie A,2010/2011,21,2011-01-23,Chievo Verona,CHI,Genoa,GEN,0,0,0,NaN,NaN,NaN
11708,Italy,Italy Serie A,2011/2012,5,2011-09-25,Chievo Verona,CHI,Genoa,GEN,2,1,3,2.50,3.2,2.8
12027,Italy,Italy Serie A,2012/2013,34,2013-04-28,Chievo Verona,CHI,Genoa,GEN,0,1,1,2.40,3.2,3.0
12327,Italy,Italy Serie A,2013/2014,27,2014-03-09,Chievo Verona,CHI,Genoa,GEN,2,1,3,2.10,3.2,3.6
12874,Italy,Italy Serie A,2014/2015,8,2014-10-26,Chievo Verona,CHI,Genoa,GEN,1,2,3,2.38,3.1,3.1
13086,Italy,Italy Serie A,2015/2016,27,2016-02-28,Chievo Verona,CHI,Genoa,GEN,1,0,1,3.00,3.0,2.5

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
10343,Italy,Italy Serie A,2008/2009,17,2008-12-21,Chievo Verona,CHI,Genoa,GEN,0,1,1,2.50,3.000000,3.000000
10959,Italy,Italy Serie A,2009/2010,4,2009-09-20,Chievo Verona,CHI,Genoa,GEN,3,1,4,2.90,3.100000,2.500000
11146,Italy,Italy Serie A,2010/2011,21,2011-01-23,Chievo Verona,CHI,Genoa,GEN,0,0,0,2.54,3.114286,2.928571
11708,Italy,Italy Serie A,2011/2012,5,2011-09-25,Chievo Verona,CHI,Genoa,GEN,2,1,3,2.50,3.200000,2.800000
12027,Italy,Italy Serie A,2012/2013,34,2013-04-28,Chievo Verona,CHI,Genoa,GEN,0,1,1,2.40,3.200000,3.000000
12327,Italy,Italy Serie A,2013/2014,27,2014-03-09,Chievo Verona,CHI,Genoa,GEN,2,1,3,2.10,3.200000,3.600000
12874,Italy,Italy Serie A,2014/2015,8,2014-10-26,Chievo Verona,CHI,Genoa,GEN,1,2,3,2.38,3.100000,3.100000
13086,Italy,Italy Serie A,2015/2016,27,2016-02-28,Chievo Verona,CHI,Genoa,GEN,1,0,1,3.00,3.000000,2.500000

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
11278,Italy,Italy Serie A,2010/2011,33,2011-04-17,Genoa,GEN,Brescia,BRE,3,0,3,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
11278,Italy,Italy Serie A,2010/2011,33,2011-04-17,Genoa,GEN,Brescia,BRE,3,0,3,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
10556,Italy,Italy Serie A,2008/2009,37,2009-05-24,Chievo Verona,CHI,Bologna,BOL,0,0,0,3.20,1.57,6.0
10777,Italy,Italy Serie A,2009/2010,22,2010-01-31,Chievo Verona,CHI,Bologna,BOL,1,1,2,2.00,3.10,4.2
11281,Italy,Italy Serie A,2010/2011,33,2011-04-17,Chievo Verona,CHI,Bologna,BOL,2,0,2,NaN,NaN,NaN
11746,Italy,Italy Serie A,2011/2012,9,2011-10-26,Chievo Verona,CHI,Bologna,BOL,0,1,1,1.80,3.25,5.0
11755,Italy,Italy Serie A,2012/2013,1,2012-08-26,Chievo Verona,CHI,Bologna,BOL,2,0,2,2.10,3.20,3.6
12364,Italy,Italy Serie A,2013/2014,30,2014-03-26,Chievo Verona,CHI,Bologna,BOL,3,0,3,2.10,3.00,4.0
13204,Italy,Italy Serie A,2015/2016,38,2016-05-15,Chievo Verona,CHI,Bologna,BOL,0,0,0,2.15,3.40,3.4

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
10556,Italy,Italy Serie A,2008/2009,37,2009-05-24,Chievo Verona,CHI,Bologna,BOL,0,0,0,3.200,1.57,6.000000
10777,Italy,Italy Serie A,2009/2010,22,2010-01-31,Chievo Verona,CHI,Bologna,BOL,1,1,2,2.000,3.10,4.200000
11281,Italy,Italy Serie A,2010/2011,33,2011-04-17,Chievo Verona,CHI,Bologna,BOL,2,0,2,2.225,2.92,4.366667
11746,Italy,Italy Serie A,2011/2012,9,2011-10-26,Chievo Verona,CHI,Bologna,BOL,0,1,1,1.800,3.25,5.000000
11755,Italy,Italy Serie A,2012/2013,1,2012-08-26,Chievo Verona,CHI,Bologna,BOL,2,0,2,2.100,3.20,3.600000
12364,Italy,Italy Serie A,2013/2014,30,2014-03-26,Chievo Verona,CHI,Bologna,BOL,3,0,3,2.100,3.00,4.000000
13204,Italy,Italy Serie A,2015/2016,38,2016-05-15,Chievo Verona,CHI,Bologna,BOL,0,0,0,2.150,3.40,3.400000

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
10608,Italy,Italy Serie A,2008/2009,7,2008-10-19,Roma,ROM,Inter,INT,0,4,4,3.40,3.00,2.30
10882,Italy,Italy Serie A,2009/2010,31,2010-03-27,Roma,ROM,Inter,INT,2,1,3,2.75,3.10,2.63
11347,Italy,Italy Serie A,2010/2011,5,2010-09-25,Roma,ROM,Inter,INT,1,0,1,3.40,3.20,2.20
11539,Italy,Italy Serie A,2011/2012,22,2012-02-05,Roma,ROM,Inter,INT,4,0,4,NaN,NaN,NaN
11887,Italy,Italy Serie A,2012/2013,21,2013-01-20,Roma,ROM,Inter,INT,1,1,2,1.91,4.00,3.40
12317,Italy,Italy Serie A,2013/2014,26,2014-03-01,Roma,ROM,Inter,INT,0,0,0,1.62,3.80,5.50
12561,Italy,Italy Serie A,2014/2015,13,2014-11-30,Roma,ROM,Inter,INT,4,2,6,1.75,3.75,4.75
13128,Italy,Italy Serie A,2015/2016,30,2016-03-19,Roma,ROM,Inter,INT,1,1,2,1.73,3.75,5.00

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
10608,Italy,Italy Serie A,2008/2009,7,2008-10-19,Roma,ROM,Inter,INT,0,4,4,3.400000,3.000000,2.300000
10882,Italy,Italy Serie A,2009/2010,31,2010-03-27,Roma,ROM,Inter,INT,2,1,3,2.750000,3.100000,2.630000
11347,Italy,Italy Serie A,2010/2011,5,2010-09-25,Roma,ROM,Inter,INT,1,0,1,3.400000,3.200000,2.200000
11539,Italy,Italy Serie A,2011/2012,22,2012-02-05,Roma,ROM,Inter,INT,4,0,4,2.365714,3.514286,3.682857
11887,Italy,Italy Serie A,2012/2013,21,2013-01-20,Roma,ROM,Inter,INT,1,1,2,1.910000,4.000000,3.400000
12317,Italy,Italy Serie A,2013/2014,26,2014-03-01,Roma,ROM,Inter,INT,0,0,0,1.620000,3.800000,5.500000
12561,Italy,Italy Serie A,2014/2015,13,2014-11-30,Roma,ROM,Inter,INT,4,2,6,1.750000,3.750000,4.750000
13128,Italy,Italy Serie A,2015/2016,30,2016-03-19,Roma,ROM,Inter,INT,1,1,2,1.730000,3.750000,5.000000

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
10261,Italy,Italy Serie A,2008/2009,1,2008-08-31,Milan,ACM,Bologna,BOL,1,2,3,1.30,4.75,12.0
10961,Italy,Italy Serie A,2009/2010,4,2009-09-20,Milan,ACM,Bologna,BOL,1,0,1,1.33,4.75,10.0
11298,Italy,Italy Serie A,2010/2011,35,2011-05-01,Milan,ACM,Bologna,BOL,1,0,1,1.20,6.50,13.0
11645,Italy,Italy Serie A,2011/2012,34,2012-04-22,Milan,ACM,Bologna,BOL,1,1,2,1.20,6.50,13.0
11884,Italy,Italy Serie A,2012/2013,21,2013-01-20,Milan,ACM,Bologna,BOL,2,1,3,NaN,NaN,NaN
12294,Italy,Italy Serie A,2013/2014,24,2014-02-14,Milan,ACM,Bologna,BOL,1,0,1,1.33,5.00,9.0
12988,Italy,Italy Serie A,2015/2016,18,2016-01-06,Milan,ACM,Bologna,BOL,0,1,1,1.50,4.20,7.0

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
10261,Italy,Italy Serie A,2008/2009,1,2008-08-31,Milan,ACM,Bologna,BOL,1,2,3,1.30,4.750000,12.000000
10961,Italy,Italy Serie A,2009/2010,4,2009-09-20,Milan,ACM,Bologna,BOL,1,0,1,1.33,4.750000,10.000000
11298,Italy,Italy Serie A,2010/2011,35,2011-05-01,Milan,ACM,Bologna,BOL,1,0,1,1.20,6.500000,13.000000
11645,Italy,Italy Serie A,2011/2012,34,2012-04-22,Milan,ACM,Bologna,BOL,1,1,2,1.20,6.500000,13.000000
11884,Italy,Italy Serie A,2012/2013,21,2013-01-20,Milan,ACM,Bologna,BOL,2,1,3,1.31,5.283333,10.666667
12294,Italy,Italy Serie A,2013/2014,24,2014-02-14,Milan,ACM,Bologna,BOL,1,0,1,1.33,5.000000,9.000000
12988,Italy,Italy Serie A,2015/2016,18,2016-01-06,Milan,ACM,Bologna,BOL,0,1,1,1.50,4.200000,7.000000

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
17696,Portugal,Portugal Liga ZON Sagres,2008/2009,15,2009-01-24,Trofense,TRO,FC Paços de Ferreira,FER,1,3,4,NaN,NaN,NaN
17707,Portugal,Portugal Liga ZON Sagres,2008/2009,17,2009-02-08,Vitória Guimarães,GUI,CS Marítimo,MAR,2,1,3,NaN,NaN,NaN
17903,Portugal,Portugal Liga ZON Sagres,2009/2010,11,2009-11-28,CD Nacional,NAC,Naval 1° de Maio,NAV,1,1,2,NaN,NaN,NaN
18351,Portugal,Portugal Liga ZON Sagres,2010/2011,8,2010-10-23,Académica de Coimbra,ACA,CD Nacional,NAC,2,1,3,NaN,NaN,NaN
18530,Portugal,Portugal Liga ZON Sagres,2011/2012,29,2012-05-05,SL Benfica,BEN,"União de Leiria, SAD",ULE,1,0,1,NaN,NaN,NaN
18551,Portugal,Portugal Liga ZON Sagres,2011/2012,30,2012-05-12,"União de Leiria, SAD",ULE,CD Nacional,NAC,2,3,5,NaN,NaN,NaN
19002,Portugal,Portugal Liga ZON Sagres,2013/2014,28,2014-04-20,SL Benfica,BEN,S.C. Olhanense,OLH,2,0,2,NaN,NaN,NaN
19223,Portugal,Portugal Liga ZON Sagres,2014/2015,23,2015-03-01,CD Nacional,NAC,Vitória Setúbal,SET,3,0,3,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
17696,Portugal,Portugal Liga ZON Sagres,2008/2009,15,2009-01-24,Trofense,TRO,FC Paços de Ferreira,FER,1,3,4,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
17696,Portugal,Portugal Liga ZON Sagres,2008/2009,15,2009-01-24,Trofense,TRO,FC Paços de Ferreira,FER,1,3,4,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
17707,Portugal,Portugal Liga ZON Sagres,2008/2009,17,2009-02-08,Vitória Guimarães,GUI,CS Marítimo,MAR,2,1,3,NaN,NaN,NaN
18071,Portugal,Portugal Liga ZON Sagres,2009/2010,30,2010-05-09,Vitória Guimarães,GUI,CS Marítimo,MAR,1,2,3,2.05,3.25,3.75
18275,Portugal,Portugal Liga ZON Sagres,2010/2011,27,2011-04-16,Vitória Guimarães,GUI,CS Marítimo,MAR,2,0,2,2.30,3.10,3.25
18468,Portugal,Portugal Liga ZON Sagres,2011/2012,21,2012-03-04,Vitória Guimarães,GUI,CS Marítimo,MAR,1,0,1,2.30,3.10,3.25
18647,Portugal,Portugal Liga ZON Sagres,2012/2013,14,2013-01-12,Vitória Guimarães,GUI,CS Marítimo,MAR,1,1,2,2.50,3.20,2.80
19062,Portugal,Portugal Liga ZON Sagres,2013/2014,7,2013-10-07,Vitória Guimarães,GUI,CS Marítimo,MAR,1,0,1,2.20,3.40,3.20
19219,Portugal,Portugal Liga ZON Sagres,2014/2015,23,2015-02-27,Vitória Guimarães,GUI,CS Marítimo,MAR,1,0,1,1.75,3.75,4.33
19426,Portugal,Portugal Liga ZON Sagres,2015/2016,13,2015-12-12,Vitória Guimarães,GUI,CS Marítimo,MAR,3,4,7,2.40,3.00,3.20

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
17707,Portugal,Portugal Liga ZON Sagres,2008/2009,17,2009-02-08,Vitória Guimarães,GUI,CS Marítimo,MAR,2,1,3,2.214286,3.257143,3.397143
18071,Portugal,Portugal Liga ZON Sagres,2009/2010,30,2010-05-09,Vitória Guimarães,GUI,CS Marítimo,MAR,1,2,3,2.050000,3.250000,3.750000
18275,Portugal,Portugal Liga ZON Sagres,2010/2011,27,2011-04-16,Vitória Guimarães,GUI,CS Marítimo,MAR,2,0,2,2.300000,3.100000,3.250000
18468,Portugal,Portugal Liga ZON Sagres,2011/2012,21,2012-03-04,Vitória Guimarães,GUI,CS Marítimo,MAR,1,0,1,2.300000,3.100000,3.250000
18647,Portugal,Portugal Liga ZON Sagres,2012/2013,14,2013-01-12,Vitória Guimarães,GUI,CS Marítimo,MAR,1,1,2,2.500000,3.200000,2.800000
19062,Portugal,Portugal Liga ZON Sagres,2013/2014,7,2013-10-07,Vitória Guimarães,GUI,CS Marítimo,MAR,1,0,1,2.200000,3.400000,3.200000
19219,Portugal,Portugal Liga ZON Sagres,2014/2015,23,2015-02-27,Vitória Guimarães,GUI,CS Marítimo,MAR,1,0,1,1.750000,3.750000,4.330000
19426,Portugal,Portugal Liga ZON Sagres,2015/2016,13,2015-12-12,Vitória Guimarães,GUI,CS Marítimo,MAR,3,4,7,2.400000,3.000000,3.200000

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
17734,Portugal,Portugal Liga ZON Sagres,2008/2009,2,2008-08-31,CD Nacional,NAC,Naval 1° de Maio,NAV,2,1,3,1.80,3.3,4.0
17903,Portugal,Portugal Liga ZON Sagres,2009/2010,11,2009-11-28,CD Nacional,NAC,Naval 1° de Maio,NAV,1,1,2,NaN,NaN,NaN
18158,Portugal,Portugal Liga ZON Sagres,2010/2011,13,2010-12-07,CD Nacional,NAC,Naval 1° de Maio,NAV,2,1,3,1.62,3.6,6.0

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
17734,Portugal,Portugal Liga ZON Sagres,2008/2009,2,2008-08-31,CD Nacional,NAC,Naval 1° de Maio,NAV,2,1,3,1.80,3.30,4.0
17903,Portugal,Portugal Liga ZON Sagres,2009/2010,11,2009-11-28,CD Nacional,NAC,Naval 1° de Maio,NAV,1,1,2,1.71,3.45,5.0
18158,Portugal,Portugal Liga ZON Sagres,2010/2011,13,2010-12-07,CD Nacional,NAC,Naval 1° de Maio,NAV,2,1,3,1.62,3.60,6.0

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
17847,Portugal,Portugal Liga ZON Sagres,2008/2009,5,2008-10-05,Académica de Coimbra,ACA,CD Nacional,NAC,1,1,2,2.38,3.1,2.88
18055,Portugal,Portugal Liga ZON Sagres,2009/2010,29,2010-05-02,Académica de Coimbra,ACA,CD Nacional,NAC,3,3,6,2.40,3.1,3.00
18351,Portugal,Portugal Liga ZON Sagres,2010/2011,8,2010-10-23,Académica de Coimbra,ACA,CD Nacional,NAC,2,1,3,NaN,NaN,NaN
18553,Portugal,Portugal Liga ZON Sagres,2011/2012,4,2011-09-12,Académica de Coimbra,ACA,CD Nacional,NAC,4,0,4,2.50,3.1,2.90
18654,Portugal,Portugal Liga ZON Sagres,2012/2013,15,2013-01-21,Académica de Coimbra,ACA,CD Nacional,NAC,2,1,3,2.50,3.2,2.88
18937,Portugal,Portugal Liga ZON Sagres,2013/2014,20,2014-02-21,Académica de Coimbra,ACA,CD Nacional,NAC,0,0,0,2.75,3.1,2.63
19235,Portugal,Portugal Liga ZON Sagres,2014/2015,25,2015-03-15,Académica de Coimbra,ACA,CD Nacional,NAC,2,1,3,3.00,3.2,2.38
19510,Portugal,Portugal Liga ZON Sagres,2015/2016,21,2016-02-07,Académica de Coimbra,ACA,CD Nacional,NAC,2,2,4,2.80,3.2,2.55

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
17847,Portugal,Portugal Liga ZON Sagres,2008/2009,5,2008-10-05,Académica de Coimbra,ACA,CD Nacional,NAC,1,1,2,2.380000,3.100000,2.880000
18055,Portugal,Portugal Liga ZON Sagres,2009/2010,29,2010-05-02,Académica de Coimbra,ACA,CD Nacional,NAC,3,3,6,2.400000,3.100000,3.000000
18351,Portugal,Portugal Liga ZON Sagres,2010/2011,8,2010-10-23,Académica de Coimbra,ACA,CD Nacional,NAC,2,1,3,2.618571,3.142857,2.745714
18553,Portugal,Portugal Liga ZON Sagres,2011/2012,4,2011-09-12,Académica de Coimbra,ACA,CD Nacional,NAC,4,0,4,2.500000,3.100000,2.900000
18654,Portugal,Portugal Liga ZON Sagres,2012/2013,15,2013-01-21,Académica de Coimbra,ACA,CD Nacional,NAC,2,1,3,2.500000,3.200000,2.880000
18937,Portugal,Portugal Liga ZON Sagres,2013/2014,20,2014-02-21,Académica de Coimbra,ACA,CD Nacional,NAC,0,0,0,2.750000,3.100000,2.630000
19235,Portugal,Portugal Liga ZON Sagres,2014/2015,25,2015-03-15,Académica de Coimbra,ACA,CD Nacional,NAC,2,1,3,3.000000,3.200000,2.380000
19510,Portugal,Portugal Liga ZON Sagres,2015/2016,21,2016-02-07,Académica de Coimbra,ACA,CD Nacional,NAC,2,2,4,2.800000,3.200000,2.550000

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
17980,Portugal,Portugal Liga ZON Sagres,2009/2010,20,2010-02-03,SL Benfica,BEN,"União de Leiria, SAD",ULE,3,0,3,1.25,5.25,13.0
18305,Portugal,Portugal Liga ZON Sagres,2010/2011,30,2011-05-14,SL Benfica,BEN,"União de Leiria, SAD",ULE,3,3,6,1.29,5.00,12.0
18530,Portugal,Portugal Liga ZON Sagres,2011/2012,29,2012-05-05,SL Benfica,BEN,"União de Leiria, SAD",ULE,1,0,1,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
17980,Portugal,Portugal Liga ZON Sagres,2009/2010,20,2010-02-03,SL Benfica,BEN,"União de Leiria, SAD",ULE,3,0,3,1.25,5.250,13.0
18305,Portugal,Portugal Liga ZON Sagres,2010/2011,30,2011-05-14,SL Benfica,BEN,"União de Leiria, SAD",ULE,3,3,6,1.29,5.000,12.0
18530,Portugal,Portugal Liga ZON Sagres,2011/2012,29,2012-05-05,SL Benfica,BEN,"União de Leiria, SAD",ULE,1,0,1,1.27,5.125,12.5

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
17908,Portugal,Portugal Liga ZON Sagres,2009/2010,12,2009-12-07,"União de Leiria, SAD",ULE,CD Nacional,NAC,1,2,3,2.5,3.0,2.75
18317,Portugal,Portugal Liga ZON Sagres,2010/2011,4,2010-09-12,"União de Leiria, SAD",ULE,CD Nacional,NAC,2,1,3,2.8,3.0,2.70
18551,Portugal,Portugal Liga ZON Sagres,2011/2012,30,2012-05-12,"União de Leiria, SAD",ULE,CD Nacional,NAC,2,3,5,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
17908,Portugal,Portugal Liga ZON Sagres,2009/2010,12,2009-12-07,"União de Leiria, SAD",ULE,CD Nacional,NAC,1,2,3,2.50,3.0,2.750
18317,Portugal,Portugal Liga ZON Sagres,2010/2011,4,2010-09-12,"União de Leiria, SAD",ULE,CD Nacional,NAC,2,1,3,2.80,3.0,2.700
18551,Portugal,Portugal Liga ZON Sagres,2011/2012,30,2012-05-12,"União de Leiria, SAD",ULE,CD Nacional,NAC,2,3,5,2.65,3.0,2.725

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
18044,Portugal,Portugal Liga ZON Sagres,2009/2010,28,2010-04-24,SL Benfica,BEN,S.C. Olhanense,OLH,5,0,5,1.17,6.5,17.0
18154,Portugal,Portugal Liga ZON Sagres,2010/2011,13,2010-12-03,SL Benfica,BEN,S.C. Olhanense,OLH,2,0,2,1.20,6.0,15.0
18594,Portugal,Portugal Liga ZON Sagres,2011/2012,9,2011-10-29,SL Benfica,BEN,S.C. Olhanense,OLH,2,1,3,1.18,6.5,16.0
18611,Portugal,Portugal Liga ZON Sagres,2012/2013,10,2012-11-24,SL Benfica,BEN,S.C. Olhanense,OLH,2,0,2,1.17,7.0,15.0
19002,Portugal,Portugal Liga ZON Sagres,2013/2014,28,2014-04-20,SL Benfica,BEN,S.C. Olhanense,OLH,2,0,2,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
18044,Portugal,Portugal Liga ZON Sagres,2009/2010,28,2010-04-24,SL Benfica,BEN,S.C. Olhanense,OLH,5,0,5,1.17,6.5,17.00
18154,Portugal,Portugal Liga ZON Sagres,2010/2011,13,2010-12-03,SL Benfica,BEN,S.C. Olhanense,OLH,2,0,2,1.20,6.0,15.00
18594,Portugal,Portugal Liga ZON Sagres,2011/2012,9,2011-10-29,SL Benfica,BEN,S.C. Olhanense,OLH,2,1,3,1.18,6.5,16.00
18611,Portugal,Portugal Liga ZON Sagres,2012/2013,10,2012-11-24,SL Benfica,BEN,S.C. Olhanense,OLH,2,0,2,1.17,7.0,15.00
19002,Portugal,Portugal Liga ZON Sagres,2013/2014,28,2014-04-20,SL Benfica,BEN,S.C. Olhanense,OLH,2,0,2,1.18,6.5,15.75

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
17855,Portugal,Portugal Liga ZON Sagres,2008/2009,6,2008-10-26,CD Nacional,NAC,Vitória Setúbal,SET,1,0,1,1.83,3.4,4.00
18119,Portugal,Portugal Liga ZON Sagres,2009/2010,9,2009-11-01,CD Nacional,NAC,Vitória Setúbal,SET,2,1,3,1.50,3.5,7.00
18358,Portugal,Portugal Liga ZON Sagres,2010/2011,9,2010-10-31,CD Nacional,NAC,Vitória Setúbal,SET,1,0,1,1.75,3.3,5.00
18398,Portugal,Portugal Liga ZON Sagres,2011/2012,13,2011-12-18,CD Nacional,NAC,Vitória Setúbal,SET,1,1,2,1.83,3.4,4.50
18602,Portugal,Portugal Liga ZON Sagres,2012/2013,1,2012-08-19,CD Nacional,NAC,Vitória Setúbal,SET,2,2,4,1.75,3.4,5.00
18861,Portugal,Portugal Liga ZON Sagres,2013/2014,11,2013-12-01,CD Nacional,NAC,Vitória Setúbal,SET,2,2,4,1.75,3.5,4.75
19223,Portugal,Portugal Liga ZON Sagres,2014/2015,23,2015-03-01,CD Nacional,NAC,Vitória Setúbal,SET,3,0,3,NaN,NaN,NaN
19663,Portugal,Portugal Liga ZON Sagres,2015/2016,6,2015-09-27,CD Nacional,NAC,Vitória Setúbal,SET,1,1,2,1.91,3.4,4.00

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
17855,Portugal,Portugal Liga ZON Sagres,2008/2009,6,2008-10-26,CD Nacional,NAC,Vitória Setúbal,SET,1,0,1,1.83,3.400000,4.000000
18119,Portugal,Portugal Liga ZON Sagres,2009/2010,9,2009-11-01,CD Nacional,NAC,Vitória Setúbal,SET,2,1,3,1.50,3.500000,7.000000
18358,Portugal,Portugal Liga ZON Sagres,2010/2011,9,2010-10-31,CD Nacional,NAC,Vitória Setúbal,SET,1,0,1,1.75,3.300000,5.000000
18398,Portugal,Portugal Liga ZON Sagres,2011/2012,13,2011-12-18,CD Nacional,NAC,Vitória Setúbal,SET,1,1,2,1.83,3.400000,4.500000
18602,Portugal,Portugal Liga ZON Sagres,2012/2013,1,2012-08-19,CD Nacional,NAC,Vitória Setúbal,SET,2,2,4,1.75,3.400000,5.000000
18861,Portugal,Portugal Liga ZON Sagres,2013/2014,11,2013-12-01,CD Nacional,NAC,Vitória Setúbal,SET,2,2,4,1.75,3.500000,4.750000
19223,Portugal,Portugal Liga ZON Sagres,2014/2015,23,2015-03-01,CD Nacional,NAC,Vitória Setúbal,SET,3,0,3,1.76,3.414286,4.892857
19663,Portugal,Portugal Liga ZON Sagres,2015/2016,6,2015-09-27,CD Nacional,NAC,Vitória Setúbal,SET,1,1,2,1.91,3.400000,4.000000

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
164,Belgium,Belgium Jupiler League,2008/2009,26,2009-03-14,Beerschot AC,BAC,RAEC Mons,MON,2,0,2,NaN,NaN,NaN
217,Belgium,Belgium Jupiler League,2008/2009,31,2009-04-26,KSV Cercle Brugge,CEB,KRC Genk,GEN,1,2,3,NaN,NaN,NaN
299,Belgium,Belgium Jupiler League,2008/2009,9,2008-10-25,RAEC Mons,MON,Beerschot AC,BAC,0,0,0,NaN,NaN,NaN
791,Belgium,Belgium Jupiler League,2011/2012,13,2011-11-05,Beerschot AC,BAC,RAEC Mons,MON,2,0,2,NaN,NaN,NaN
923,Belgium,Belgium Jupiler League,2011/2012,28,2012-03-03,RAEC Mons,MON,Beerschot AC,BAC,4,2,6,NaN,NaN,NaN
1126,Belgium,Belgium Jupiler League,2012/2013,24,2013-01-26,Beerschot AC,BAC,RAEC Mons,MON,0,0,0,NaN,NaN,NaN
1196,Belgium,Belgium Jupiler League,2012/2013,5,2012-08-26,Standard de Liège,STL,KV Mechelen,MEC,3,2,5,NaN,NaN,NaN
1197,Belgium,Belgium Jupiler League,2012/2013,5,2012-08-26,KRC Genk,GEN,SV Zulte-Waregem,ZUL,2,0,2,NaN,NaN,NaN
1202,Belgium,Belgium Jupiler League,2012/2013,5,2012-08-26,RAEC Mons,MON,Club Brugge KV,CLB,1,3,4,NaN,NaN,NaN
1234,Belgium,Belgium Jupiler League,2012/2013,9,2012-09-29,RAEC Mons,MON,Beerschot AC,BAC,1,0,1,NaN,NaN,NaN
1236,Belgium,Belgium Jupiler League,2013/2014,1,2014-03-29,Waasland-Beveren,WAA,Lierse SK,LIE,2,0,2,NaN,NaN,NaN
1237,Belgium,Belgium Jupiler League,2013/2014,1,2014-03-29,KAA Gent,GEN,KV Oostende,OOS,0,1,1,NaN,NaN,NaN
1238,Belgium,Belgium Jupiler League,2013/2014,2,2014-04-05,Lierse SK,LIE,KAA Gent,GEN,1,0,1,NaN,NaN,NaN
1239,Belgium,Belgium Jupiler League,2013/2014,2,2014-04-05,KV Oostende,OOS,Waasland-Beveren,WAA,0,0,0,NaN,NaN,NaN
1240,Belgium,Belgium Jupiler League,2013/2014,3,2014-04-12,KAA Gent,GEN,Waasland-Beveren,WAA,2,1,3,NaN,NaN,NaN
1241,Belgium,Belgium Jupiler League,2013/2014,3,2014-04-12,KV Oostende,OOS,Lierse SK,LIE,2,0,2,NaN,NaN,NaN
1242,Belgium,Belgium Jupiler League,2013/2014,4,2014-04-19,Waasland-Beveren,WAA,KAA Gent,GEN,2,4,6,NaN,NaN,NaN
1243,Belgium,Belgium Jupiler League,2013/2014,4,2014-04-19,Lierse SK,LIE,KV Oostende,OOS,0,2,2,NaN,NaN,NaN
1244,Belgium,Belgium Jupiler League,2013/2014,5,2014-04-26,Lierse SK,LIE,Waasland-Beveren,WAA,4,2,6,NaN,NaN,NaN
1245,Belgium,Belgium Jupiler League,2013/2014,5,2014-04-26,KV Oostende,OOS,KAA Gent,GEN,1,1,2,NaN,NaN,NaN
1246,Belgium,Belgium Jupiler League,2013/2014,6,2014-05-03,Waasland-Beveren,WAA,KV Oostende,OOS,0,1,1,NaN,NaN,NaN
1247,Belgium,Belgium Jupiler League,2013/2014,6,2014-05-03,KAA Gent,GEN,Lierse SK,LIE,4,0,4,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
164,Belgium,Belgium Jupiler League,2008/2009,26,2009-03-14,Beerschot AC,BAC,RAEC Mons,MON,2,0,2,NaN,NaN,NaN
791,Belgium,Belgium Jupiler League,2011/2012,13,2011-11-05,Beerschot AC,BAC,RAEC Mons,MON,2,0,2,NaN,NaN,NaN
1126,Belgium,Belgium Jupiler League,2012/2013,24,2013-01-26,Beerschot AC,BAC,RAEC Mons,MON,0,0,0,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
164,Belgium,Belgium Jupiler League,2008/2009,26,2009-03-14,Beerschot AC,BAC,RAEC Mons,MON,2,0,2,NaN,NaN,NaN
791,Belgium,Belgium Jupiler League,2011/2012,13,2011-11-05,Beerschot AC,BAC,RAEC Mons,MON,2,0,2,NaN,NaN,NaN
1126,Belgium,Belgium Jupiler League,2012/2013,24,2013-01-26,Beerschot AC,BAC,RAEC Mons,MON,0,0,0,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
217,Belgium,Belgium Jupiler League,2008/2009,31,2009-04-26,KSV Cercle Brugge,CEB,KRC Genk,GEN,1,2,3,NaN,NaN,NaN
448,Belgium,Belgium Jupiler League,2009/2010,28,2010-02-27,KSV Cercle Brugge,CEB,KRC Genk,GEN,1,0,1,2.50,3.25,2.80
707,Belgium,Belgium Jupiler League,2010/2011,30,2011-03-20,KSV Cercle Brugge,CEB,KRC Genk,GEN,0,1,1,3.30,3.30,2.05
954,Belgium,Belgium Jupiler League,2011/2012,4,2011-08-20,KSV Cercle Brugge,CEB,KRC Genk,GEN,3,2,5,3.30,3.30,2.20
1059,Belgium,Belgium Jupiler League,2012/2013,16,2012-11-17,KSV Cercle Brugge,CEB,KRC Genk,GEN,3,1,4,3.25,3.50,2.10
1319,Belgium,Belgium Jupiler League,2014/2015,17,2014-11-29,KSV Cercle Brugge,CEB,KRC Genk,GEN,0,1,1,4.00,3.40,1.91

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
217,Belgium,Belgium Jupiler League,2008/2009,31,2009-04-26,KSV Cercle Brugge,CEB,KRC Genk,GEN,1,2,3,3.27,3.35,2.212
448,Belgium,Belgium Jupiler League,2009/2010,28,2010-02-27,KSV Cercle Brugge,CEB,KRC Genk,GEN,1,0,1,2.50,3.25,2.800
707,Belgium,Belgium Jupiler League,2010/2011,30,2011-03-20,KSV Cercle Brugge,CEB,KRC Genk,GEN,0,1,1,3.30,3.30,2.050
954,Belgium,Belgium Jupiler League,2011/2012,4,2011-08-20,KSV Cercle Brugge,CEB,KRC Genk,GEN,3,2,5,3.30,3.30,2.200
1059,Belgium,Belgium Jupiler League,2012/2013,16,2012-11-17,KSV Cercle Brugge,CEB,KRC Genk,GEN,3,1,4,3.25,3.50,2.100
1319,Belgium,Belgium Jupiler League,2014/2015,17,2014-11-29,KSV Cercle Brugge,CEB,KRC Genk,GEN,0,1,1,4.00,3.40,1.910

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
299,Belgium,Belgium Jupiler League,2008/2009,9,2008-10-25,RAEC Mons,MON,Beerschot AC,BAC,0,0,0,NaN,NaN,NaN
923,Belgium,Belgium Jupiler League,2011/2012,28,2012-03-03,RAEC Mons,MON,Beerschot AC,BAC,4,2,6,NaN,NaN,NaN
1234,Belgium,Belgium Jupiler League,2012/2013,9,2012-09-29,RAEC Mons,MON,Beerschot AC,BAC,1,0,1,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
299,Belgium,Belgium Jupiler League,2008/2009,9,2008-10-25,RAEC Mons,MON,Beerschot AC,BAC,0,0,0,NaN,NaN,NaN
923,Belgium,Belgium Jupiler League,2011/2012,28,2012-03-03,RAEC Mons,MON,Beerschot AC,BAC,4,2,6,NaN,NaN,NaN
1234,Belgium,Belgium Jupiler League,2012/2013,9,2012-09-29,RAEC Mons,MON,Beerschot AC,BAC,1,0,1,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
164,Belgium,Belgium Jupiler League,2008/2009,26,2009-03-14,Beerschot AC,BAC,RAEC Mons,MON,2,0,2,NaN,NaN,NaN
791,Belgium,Belgium Jupiler League,2011/2012,13,2011-11-05,Beerschot AC,BAC,RAEC Mons,MON,2,0,2,NaN,NaN,NaN
1126,Belgium,Belgium Jupiler League,2012/2013,24,2013-01-26,Beerschot AC,BAC,RAEC Mons,MON,0,0,0,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
164,Belgium,Belgium Jupiler League,2008/2009,26,2009-03-14,Beerschot AC,BAC,RAEC Mons,MON,2,0,2,NaN,NaN,NaN
791,Belgium,Belgium Jupiler League,2011/2012,13,2011-11-05,Beerschot AC,BAC,RAEC Mons,MON,2,0,2,NaN,NaN,NaN
1126,Belgium,Belgium Jupiler League,2012/2013,24,2013-01-26,Beerschot AC,BAC,RAEC Mons,MON,0,0,0,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
299,Belgium,Belgium Jupiler League,2008/2009,9,2008-10-25,RAEC Mons,MON,Beerschot AC,BAC,0,0,0,NaN,NaN,NaN
923,Belgium,Belgium Jupiler League,2011/2012,28,2012-03-03,RAEC Mons,MON,Beerschot AC,BAC,4,2,6,NaN,NaN,NaN
1234,Belgium,Belgium Jupiler League,2012/2013,9,2012-09-29,RAEC Mons,MON,Beerschot AC,BAC,1,0,1,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
299,Belgium,Belgium Jupiler League,2008/2009,9,2008-10-25,RAEC Mons,MON,Beerschot AC,BAC,0,0,0,NaN,NaN,NaN
923,Belgium,Belgium Jupiler League,2011/2012,28,2012-03-03,RAEC Mons,MON,Beerschot AC,BAC,4,2,6,NaN,NaN,NaN
1234,Belgium,Belgium Jupiler League,2012/2013,9,2012-09-29,RAEC Mons,MON,Beerschot AC,BAC,1,0,1,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
164,Belgium,Belgium Jupiler League,2008/2009,26,2009-03-14,Beerschot AC,BAC,RAEC Mons,MON,2,0,2,NaN,NaN,NaN
791,Belgium,Belgium Jupiler League,2011/2012,13,2011-11-05,Beerschot AC,BAC,RAEC Mons,MON,2,0,2,NaN,NaN,NaN
1126,Belgium,Belgium Jupiler League,2012/2013,24,2013-01-26,Beerschot AC,BAC,RAEC Mons,MON,0,0,0,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
164,Belgium,Belgium Jupiler League,2008/2009,26,2009-03-14,Beerschot AC,BAC,RAEC Mons,MON,2,0,2,NaN,NaN,NaN
791,Belgium,Belgium Jupiler League,2011/2012,13,2011-11-05,Beerschot AC,BAC,RAEC Mons,MON,2,0,2,NaN,NaN,NaN
1126,Belgium,Belgium Jupiler League,2012/2013,24,2013-01-26,Beerschot AC,BAC,RAEC Mons,MON,0,0,0,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
221,Belgium,Belgium Jupiler League,2008/2009,31,2009-04-25,Standard de Liège,STL,KV Mechelen,MEC,4,1,5,1.18,6.00,13.0
489,Belgium,Belgium Jupiler League,2009/2010,6,2009-09-12,Standard de Liège,STL,KV Mechelen,MEC,3,0,3,1.36,4.75,8.5
629,Belgium,Belgium Jupiler League,2010/2011,22,2011-02-26,Standard de Liège,STL,KV Mechelen,MEC,3,0,3,1.62,3.60,5.0
804,Belgium,Belgium Jupiler League,2011/2012,15,2011-11-25,Standard de Liège,STL,KV Mechelen,MEC,3,2,5,1.40,4.33,8.5
1196,Belgium,Belgium Jupiler League,2012/2013,5,2012-08-26,Standard de Liège,STL,KV Mechelen,MEC,3,2,5,NaN,NaN,NaN
1289,Belgium,Belgium Jupiler League,2014/2015,14,2014-11-01,Standard de Liège,STL,KV Mechelen,MEC,2,0,2,1.62,3.80,5.5
1521,Belgium,Belgium Jupiler League,2015/2016,13,2015-10-28,Standard de Liège,STL,KV Mechelen,MEC,2,1,3,1.85,3.50,4.2

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
221,Belgium,Belgium Jupiler League,2008/2009,31,2009-04-25,Standard de Liège,STL,KV Mechelen,MEC,4,1,5,1.180,6.00,13.00
489,Belgium,Belgium Jupiler League,2009/2010,6,2009-09-12,Standard de Liège,STL,KV Mechelen,MEC,3,0,3,1.360,4.75,8.50
629,Belgium,Belgium Jupiler League,2010/2011,22,2011-02-26,Standard de Liège,STL,KV Mechelen,MEC,3,0,3,1.620,3.60,5.00
804,Belgium,Belgium Jupiler League,2011/2012,15,2011-11-25,Standard de Liège,STL,KV Mechelen,MEC,3,2,5,1.400,4.33,8.50
1196,Belgium,Belgium Jupiler League,2012/2013,5,2012-08-26,Standard de Liège,STL,KV Mechelen,MEC,3,2,5,1.505,4.33,7.45
1289,Belgium,Belgium Jupiler League,2014/2015,14,2014-11-01,Standard de Liège,STL,KV Mechelen,MEC,2,0,2,1.620,3.80,5.50
1521,Belgium,Belgium Jupiler League,2015/2016,13,2015-10-28,Standard de Liège,STL,KV Mechelen,MEC,2,1,3,1.850,3.50,4.20

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
120,Belgium,Belgium Jupiler League,2008/2009,21,2009-02-07,KRC Genk,GEN,SV Zulte-Waregem,ZUL,1,2,3,1.66,3.4,4.75
377,Belgium,Belgium Jupiler League,2009/2010,19,2009-12-19,KRC Genk,GEN,SV Zulte-Waregem,ZUL,2,2,4,2.20,3.3,3.25
750,Belgium,Belgium Jupiler League,2010/2011,9,2010-09-25,KRC Genk,GEN,SV Zulte-Waregem,ZUL,3,0,3,1.53,4.0,6.00
933,Belgium,Belgium Jupiler League,2011/2012,3,2011-08-13,KRC Genk,GEN,SV Zulte-Waregem,ZUL,2,2,4,1.50,4.2,6.50
1197,Belgium,Belgium Jupiler League,2012/2013,5,2012-08-26,KRC Genk,GEN,SV Zulte-Waregem,ZUL,2,0,2,NaN,NaN,NaN
1417,Belgium,Belgium Jupiler League,2014/2015,29,2015-03-07,KRC Genk,GEN,SV Zulte-Waregem,ZUL,3,2,5,1.83,3.5,4.33
1602,Belgium,Belgium Jupiler League,2015/2016,22,2016-01-15,KRC Genk,GEN,SV Zulte-Waregem,ZUL,2,1,3,1.75,3.6,4.60

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
120,Belgium,Belgium Jupiler League,2008/2009,21,2009-02-07,KRC Genk,GEN,SV Zulte-Waregem,ZUL,1,2,3,1.660,3.400000,4.750
377,Belgium,Belgium Jupiler League,2009/2010,19,2009-12-19,KRC Genk,GEN,SV Zulte-Waregem,ZUL,2,2,4,2.200,3.300000,3.250
750,Belgium,Belgium Jupiler League,2010/2011,9,2010-09-25,KRC Genk,GEN,SV Zulte-Waregem,ZUL,3,0,3,1.530,4.000000,6.000
933,Belgium,Belgium Jupiler League,2011/2012,3,2011-08-13,KRC Genk,GEN,SV Zulte-Waregem,ZUL,2,2,4,1.500,4.200000,6.500
1197,Belgium,Belgium Jupiler League,2012/2013,5,2012-08-26,KRC Genk,GEN,SV Zulte-Waregem,ZUL,2,0,2,1.745,3.666667,4.905
1417,Belgium,Belgium Jupiler League,2014/2015,29,2015-03-07,KRC Genk,GEN,SV Zulte-Waregem,ZUL,3,2,5,1.830,3.500000,4.330
1602,Belgium,Belgium Jupiler League,2015/2016,22,2016-01-15,KRC Genk,GEN,SV Zulte-Waregem,ZUL,2,1,3,1.750,3.600000,4.600

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
38,Belgium,Belgium Jupiler League,2008/2009,13,2008-11-22,RAEC Mons,MON,Club Brugge KV,CLB,1,2,3,4.33,3.4,1.85
881,Belgium,Belgium Jupiler League,2011/2012,23,2012-01-29,RAEC Mons,MON,Club Brugge KV,CLB,0,2,2,3.50,3.5,2.00
1202,Belgium,Belgium Jupiler League,2012/2013,5,2012-08-26,RAEC Mons,MON,Club Brugge KV,CLB,1,3,4,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
38,Belgium,Belgium Jupiler League,2008/2009,13,2008-11-22,RAEC Mons,MON,Club Brugge KV,CLB,1,2,3,4.330,3.40,1.850
881,Belgium,Belgium Jupiler League,2011/2012,23,2012-01-29,RAEC Mons,MON,Club Brugge KV,CLB,0,2,2,3.500,3.50,2.000
1202,Belgium,Belgium Jupiler League,2012/2013,5,2012-08-26,RAEC Mons,MON,Club Brugge KV,CLB,1,3,4,3.915,3.45,1.925

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
299,Belgium,Belgium Jupiler League,2008/2009,9,2008-10-25,RAEC Mons,MON,Beerschot AC,BAC,0,0,0,NaN,NaN,NaN
923,Belgium,Belgium Jupiler League,2011/2012,28,2012-03-03,RAEC Mons,MON,Beerschot AC,BAC,4,2,6,NaN,NaN,NaN
1234,Belgium,Belgium Jupiler League,2012/2013,9,2012-09-29,RAEC Mons,MON,Beerschot AC,BAC,1,0,1,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
299,Belgium,Belgium Jupiler League,2008/2009,9,2008-10-25,RAEC Mons,MON,Beerschot AC,BAC,0,0,0,NaN,NaN,NaN
923,Belgium,Belgium Jupiler League,2011/2012,28,2012-03-03,RAEC Mons,MON,Beerschot AC,BAC,4,2,6,NaN,NaN,NaN
1234,Belgium,Belgium Jupiler League,2012/2013,9,2012-09-29,RAEC Mons,MON,Beerschot AC,BAC,1,0,1,NaN,NaN,NaN

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
1227,Belgium,Belgium Jupiler League,2012/2013,8,2012-09-22,Waasland-Beveren,WAA,Lierse SK,LIE,1,1,2,2.40,3.4,2.8
1236,Belgium,Belgium Jupiler League,2013/2014,1,2014-03-29,Waasland-Beveren,WAA,Lierse SK,LIE,2,0,2,NaN,NaN,NaN
1463,Belgium,Belgium Jupiler League,2014/2015,6,2014-08-30,Waasland-Beveren,WAA,Lierse SK,LIE,2,0,2,2.05,3.3,3.6

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
1227,Belgium,Belgium Jupiler League,2012/2013,8,2012-09-22,Waasland-Beveren,WAA,Lierse SK,LIE,1,1,2,2.400,3.40,2.8
1236,Belgium,Belgium Jupiler League,2013/2014,1,2014-03-29,Waasland-Beveren,WAA,Lierse SK,LIE,2,0,2,2.225,3.35,3.2
1463,Belgium,Belgium Jupiler League,2014/2015,6,2014-08-30,Waasland-Beveren,WAA,Lierse SK,LIE,2,0,2,2.050,3.30,3.6

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
1237,Belgium,Belgium Jupiler League,2013/2014,1,2014-03-29,KAA Gent,GEN,KV Oostende,OOS,0,1,1,NaN,NaN,NaN
1370,Belgium,Belgium Jupiler League,2014/2015,23,2015-01-25,KAA Gent,GEN,KV Oostende,OOS,3,1,4,1.4,4.5,8.0
1513,Belgium,Belgium Jupiler League,2015/2016,12,2015-10-24,KAA Gent,GEN,KV Oostende,OOS,2,2,4,1.4,4.5,8.0

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
1237,Belgium,Belgium Jupiler League,2013/2014,1,2014-03-29,KAA Gent,GEN,KV Oostende,OOS,0,1,1,1.4,4.5,8.0
1370,Belgium,Belgium Jupiler League,2014/2015,23,2015-01-25,KAA Gent,GEN,KV Oostende,OOS,3,1,4,1.4,4.5,8.0
1513,Belgium,Belgium Jupiler League,2015/2016,12,2015-10-24,KAA Gent,GEN,KV Oostende,OOS,2,2,4,1.4,4.5,8.0

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
731,Belgium,Belgium Jupiler League,2010/2011,6,2010-09-11,Lierse SK,LIE,KAA Gent,GEN,2,2,4,5.00,3.75,1.67
858,Belgium,Belgium Jupiler League,2011/2012,20,2012-01-14,Lierse SK,LIE,KAA Gent,GEN,2,1,3,5.00,3.75,1.67
1057,Belgium,Belgium Jupiler League,2012/2013,16,2012-11-17,Lierse SK,LIE,KAA Gent,GEN,2,0,2,3.60,3.50,2.00
1238,Belgium,Belgium Jupiler League,2013/2014,2,2014-04-05,Lierse SK,LIE,KAA Gent,GEN,1,0,1,NaN,NaN,NaN
1292,Belgium,Belgium Jupiler League,2014/2015,14,2014-11-02,Lierse SK,LIE,KAA Gent,GEN,0,1,1,4.75,3.60,1.73

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
731,Belgium,Belgium Jupiler League,2010/2011,6,2010-09-11,Lierse SK,LIE,KAA Gent,GEN,2,2,4,5.0000,3.75,1.6700
858,Belgium,Belgium Jupiler League,2011/2012,20,2012-01-14,Lierse SK,LIE,KAA Gent,GEN,2,1,3,5.0000,3.75,1.6700
1057,Belgium,Belgium Jupiler League,2012/2013,16,2012-11-17,Lierse SK,LIE,KAA Gent,GEN,2,0,2,3.6000,3.50,2.0000
1238,Belgium,Belgium Jupiler League,2013/2014,2,2014-04-05,Lierse SK,LIE,KAA Gent,GEN,1,0,1,4.5875,3.65,1.7675
1292,Belgium,Belgium Jupiler League,2014/2015,14,2014-11-02,Lierse SK,LIE,KAA Gent,GEN,0,1,1,4.7500,3.60,1.7300

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
1239,Belgium,Belgium Jupiler League,2013/2014,2,2014-04-05,KV Oostende,OOS,Waasland-Beveren,WAA,0,0,0,NaN,NaN,NaN
1419,Belgium,Belgium Jupiler League,2014/2015,29,2015-03-07,KV Oostende,OOS,Waasland-Beveren,WAA,4,3,7,1.91,3.4,4.0
1603,Belgium,Belgium Jupiler League,2015/2016,22,2016-01-17,KV Oostende,OOS,Waasland-Beveren,WAA,3,3,6,1.44,4.5,6.5

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
1239,Belgium,Belgium Jupiler League,2013/2014,2,2014-04-05,KV Oostende,OOS,Waasland-Beveren,WAA,0,0,0,1.675,3.95,5.25
1419,Belgium,Belgium Jupiler League,2014/2015,29,2015-03-07,KV Oostende,OOS,Waasland-Beveren,WAA,4,3,7,1.910,3.40,4.00
1603,Belgium,Belgium Jupiler League,2015/2016,22,2016-01-17,KV Oostende,OOS,Waasland-Beveren,WAA,3,3,6,1.440,4.50,6.50

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
1078,Belgium,Belgium Jupiler League,2012/2013,19,2012-12-08,KAA Gent,GEN,Waasland-Beveren,WAA,0,2,2,1.4,4.75,7.5
1240,Belgium,Belgium Jupiler League,2013/2014,3,2014-04-12,KAA Gent,GEN,Waasland-Beveren,WAA,2,1,3,NaN,NaN,NaN
1281,Belgium,Belgium Jupiler League,2014/2015,13,2014-10-29,KAA Gent,GEN,Waasland-Beveren,WAA,4,1,5,1.4,4.50,7.5
1617,Belgium,Belgium Jupiler League,2015/2016,24,2016-01-31,KAA Gent,GEN,Waasland-Beveren,WAA,2,1,3,1.2,7.00,11.0

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
1078,Belgium,Belgium Jupiler League,2012/2013,19,2012-12-08,KAA Gent,GEN,Waasland-Beveren,WAA,0,2,2,1.400000,4.750000,7.500000
1240,Belgium,Belgium Jupiler League,2013/2014,3,2014-04-12,KAA Gent,GEN,Waasland-Beveren,WAA,2,1,3,1.333333,5.416667,8.666667
1281,Belgium,Belgium Jupiler League,2014/2015,13,2014-10-29,KAA Gent,GEN,Waasland-Beveren,WAA,4,1,5,1.400000,4.500000,7.500000
1617,Belgium,Belgium Jupiler League,2015/2016,24,2016-01-31,KAA Gent,GEN,Waasland-Beveren,WAA,2,1,3,1.200000,7.000000,11.000000

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
1241,Belgium,Belgium Jupiler League,2013/2014,3,2014-04-12,KV Oostende,OOS,Lierse SK,LIE,2,0,2,NaN,NaN,NaN
1322,Belgium,Belgium Jupiler League,2014/2015,18,2014-12-06,KV Oostende,OOS,Lierse SK,LIE,2,1,3,1.75,3.75,4.5

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
1241,Belgium,Belgium Jupiler League,2013/2014,3,2014-04-12,KV Oostende,OOS,Lierse SK,LIE,2,0,2,1.75,3.75,4.5
1322,Belgium,Belgium Jupiler League,2014/2015,18,2014-12-06,KV Oostende,OOS,Lierse SK,LIE,2,1,3,1.75,3.75,4.5

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
1195,Belgium,Belgium Jupiler League,2012/2013,4,2012-08-18,Waasland-Beveren,WAA,KAA Gent,GEN,0,2,2,4.50,3.75,1.75
1242,Belgium,Belgium Jupiler League,2013/2014,4,2014-04-19,Waasland-Beveren,WAA,KAA Gent,GEN,2,4,6,NaN,NaN,NaN
1415,Belgium,Belgium Jupiler League,2014/2015,28,2015-03-01,Waasland-Beveren,WAA,KAA Gent,GEN,0,1,1,5.50,3.75,1.62
1727,Belgium,Belgium Jupiler League,2015/2016,9,2015-09-26,Waasland-Beveren,WAA,KAA Gent,GEN,1,3,4,5.25,4.20,1.57

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
1195,Belgium,Belgium Jupiler League,2012/2013,4,2012-08-18,Waasland-Beveren,WAA,KAA Gent,GEN,0,2,2,4.500000,3.75,1.750000
1242,Belgium,Belgium Jupiler League,2013/2014,4,2014-04-19,Waasland-Beveren,WAA,KAA Gent,GEN,2,4,6,5.083333,3.90,1.646667
1415,Belgium,Belgium Jupiler League,2014/2015,28,2015-03-01,Waasland-Beveren,WAA,KAA Gent,GEN,0,1,1,5.500000,3.75,1.620000
1727,Belgium,Belgium Jupiler League,2015/2016,9,2015-09-26,Waasland-Beveren,WAA,KAA Gent,GEN,1,3,4,5.250000,4.20,1.570000

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
1243,Belgium,Belgium Jupiler League,2013/2014,4,2014-04-19,Lierse SK,LIE,KV Oostende,OOS,0,2,2,NaN,NaN,NaN
1251,Belgium,Belgium Jupiler League,2014/2015,1,2014-07-26,Lierse SK,LIE,KV Oostende,OOS,2,0,2,2.4,3.2,3.0

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
1243,Belgium,Belgium Jupiler League,2013/2014,4,2014-04-19,Lierse SK,LIE,KV Oostende,OOS,0,2,2,2.4,3.2,3.0
1251,Belgium,Belgium Jupiler League,2014/2015,1,2014-07-26,Lierse SK,LIE,KV Oostende,OOS,2,0,2,2.4,3.2,3.0

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
1121,Belgium,Belgium Jupiler League,2012/2013,23,2013-01-19,Lierse SK,LIE,Waasland-Beveren,WAA,0,0,0,2.00,3.4,3.75
1244,Belgium,Belgium Jupiler League,2013/2014,5,2014-04-26,Lierse SK,LIE,Waasland-Beveren,WAA,4,2,6,NaN,NaN,NaN
1374,Belgium,Belgium Jupiler League,2014/2015,23,2015-01-24,Lierse SK,LIE,Waasland-Beveren,WAA,1,1,2,2.05,3.4,3.50

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
1121,Belgium,Belgium Jupiler League,2012/2013,23,2013-01-19,Lierse SK,LIE,Waasland-Beveren,WAA,0,0,0,2.000,3.4,3.750
1244,Belgium,Belgium Jupiler League,2013/2014,5,2014-04-26,Lierse SK,LIE,Waasland-Beveren,WAA,4,2,6,2.025,3.4,3.625
1374,Belgium,Belgium Jupiler League,2014/2015,23,2015-01-24,Lierse SK,LIE,Waasland-Beveren,WAA,1,1,2,2.050,3.4,3.500

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
1245,Belgium,Belgium Jupiler League,2013/2014,5,2014-04-26,KV Oostende,OOS,KAA Gent,GEN,1,1,2,NaN,NaN,NaN
1474,Belgium,Belgium Jupiler League,2014/2015,8,2014-09-20,KV Oostende,OOS,KAA Gent,GEN,1,3,4,3.0,3.25,2.38
1642,Belgium,Belgium Jupiler League,2015/2016,27,2016-02-21,KV Oostende,OOS,KAA Gent,GEN,5,2,7,3.6,3.60,1.95

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
1245,Belgium,Belgium Jupiler League,2013/2014,5,2014-04-26,KV Oostende,OOS,KAA Gent,GEN,1,1,2,3.3,3.425,2.165
1474,Belgium,Belgium Jupiler League,2014/2015,8,2014-09-20,KV Oostende,OOS,KAA Gent,GEN,1,3,4,3.0,3.250,2.380
1642,Belgium,Belgium Jupiler League,2015/2016,27,2016-02-21,KV Oostende,OOS,KAA Gent,GEN,5,2,7,3.6,3.600,1.950

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
1246,Belgium,Belgium Jupiler League,2013/2014,6,2014-05-03,Waasland-Beveren,WAA,KV Oostende,OOS,0,1,1,NaN,NaN,NaN
1294,Belgium,Belgium Jupiler League,2014/2015,14,2014-11-01,Waasland-Beveren,WAA,KV Oostende,OOS,1,0,1,3.2,3.3,2.25
1710,Belgium,Belgium Jupiler League,2015/2016,7,2015-09-12,Waasland-Beveren,WAA,KV Oostende,OOS,1,5,6,3.1,3.6,2.15

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
1246,Belgium,Belgium Jupiler League,2013/2014,6,2014-05-03,Waasland-Beveren,WAA,KV Oostende,OOS,0,1,1,3.15,3.45,2.20
1294,Belgium,Belgium Jupiler League,2014/2015,14,2014-11-01,Waasland-Beveren,WAA,KV Oostende,OOS,1,0,1,3.20,3.30,2.25
1710,Belgium,Belgium Jupiler League,2015/2016,7,2015-09-12,Waasland-Beveren,WAA,KV Oostende,OOS,1,5,6,3.10,3.60,2.15

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
653,Belgium,Belgium Jupiler League,2010/2011,25,2011-02-04,KAA Gent,GEN,Lierse SK,LIE,4,1,5,1.29,5.00,11.0
958,Belgium,Belgium Jupiler League,2011/2012,5,2011-08-27,KAA Gent,GEN,Lierse SK,LIE,1,0,1,1.36,4.75,8.0
1002,Belgium,Belgium Jupiler League,2012/2013,1,2012-07-29,KAA Gent,GEN,Lierse SK,LIE,2,0,2,1.30,5.00,11.0
1247,Belgium,Belgium Jupiler League,2013/2014,6,2014-05-03,KAA Gent,GEN,Lierse SK,LIE,4,0,4,NaN,NaN,NaN
1418,Belgium,Belgium Jupiler League,2014/2015,29,2015-03-07,KAA Gent,GEN,Lierse SK,LIE,2,1,3,1.25,5.75,11.0

,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
653,Belgium,Belgium Jupiler League,2010/2011,25,2011-02-04,KAA Gent,GEN,Lierse SK,LIE,4,1,5,1.29,5.000,11.00
958,Belgium,Belgium Jupiler League,2011/2012,5,2011-08-27,KAA Gent,GEN,Lierse SK,LIE,1,0,1,1.36,4.750,8.00
1002,Belgium,Belgium Jupiler League,2012/2013,1,2012-07-29,KAA Gent,GEN,Lierse SK,LIE,2,0,2,1.30,5.000,11.00
1247,Belgium,Belgium Jupiler League,2013/2014,6,2014-05-03,KAA Gent,GEN,Lierse SK,LIE,4,0,4,1.30,5.125,10.25
1418,Belgium,Belgium Jupiler League,2014/2015,29,2015-03-07,KAA Gent,GEN,Lierse SK,LIE,2,1,3,1.25,5.750,11.00

In [18]:
#observamos el resultado...

match_df['B365H'].isnull().groupby(match_df['league_name']).agg({'NaN':sum}).sort_values('NaN', ascending = True).reset_index()

                 league_name     NaN
0     England Premier League     0.0
1             France Ligue 1     0.0
2      Germany 1. Bundesliga     0.0
3     Netherlands Eredivisie     0.0
4    Scotland Premier League     0.0
5            Spain LIGA BBVA     0.0
6              Italy Serie A     1.0
7   Portugal Liga ZON Sagres     1.0
8     Belgium Jupiler League     6.0
9   Switzerland Super League  1422.0
10        Poland Ekstraklasa  1920.0

In [19]:
#reemplazamos por 0 los valores NaN que nos quedan...

match_df.fillna(0, inplace = True)

match_df.isnull().sum()

country_name            0
league_name             0
season                  0
stage                   0
date                    0
home_team_long_name     0
home_short_long_name    0
away_team_long_name     0
away_short_long_name    0
home_team_goal          0
away_team_goal          0
total_goal              0
B365H                   0
B365D                   0
B365A                   0
dtype: int64

# 5. Normalizacion de columnas

Primero que todo la notación:
* $x = [x_1, x_2, ..., x_n]$
* $\mu$: Media
* $\sigma$: Desviacion Estandar

Ahora normalizaremos algunas de las columnas del Dataframe, para ello usaremos dos tipos de normalizacion:

* Min-Max:  
$$
z_i = \frac{x_i - min(x)}{max(x) - min(x)}
$$
* Z-score
$$
z_i = \frac{x_i - \mu}{\sigma}
$$

Normalizar la columna `crossing` usando **Min-Max**.

Normalizar la columna `short_passing` usando **Z-score**.

**Hints**:
* https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html#sklearn.preprocessing.MinMaxScaler
* https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.zscore.html

### Min-Max

In [20]:
# TODO
from sklearn.preprocessing import MinMaxScaler

pre = player_df['crossing'].head().copy()
minmaxscaler = MinMaxScaler()
player_df['crossing'] = minmaxscaler.fit_transform(player_df['crossing'].values.reshape(-1, 1))
pos = player_df['crossing'].head().copy()

siamesas(pd.DataFrame(pre).rename(columns={'crossing': 'crossing(pre)'}), pd.DataFrame(pos).rename(columns={'crossing': 'crossing(pos)'}))

### Z-score

In [21]:
# TODO
from scipy import stats

pre = player_df['short_passing'].head().copy()
player_df['short_passing'] = stats.zscore(player_df['short_passing'])
pos = player_df['short_passing'].head().copy()

siamesas(pd.DataFrame(pre).rename(columns={'short_passing': 'short_passing(pre)'}), pd.DataFrame(pos).rename(columns={'short_passing': 'short_passing(pos)'}))

# 6. Codificar variables

> Las variables categóricas deben ser etiquetadas como variables numéricas, no como cadenas.

Codificar la variable `country_name` del Dataframe `match_df`

In [22]:
# TODO

match_df.country_name.value_counts()

France         3040
Spain          3040
England        3040
Italy          3017
Germany        2448
Netherlands    2448
Portugal       2052
Poland         1920
Scotland       1824
Belgium        1728
Switzerland    1422
Name: country_name, dtype: int64

More about preprocessing in:
* https://scikit-learn.org/stable/modules/classes.html#module-sklearn.preprocessing

In [23]:
#
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
xx = le.fit_transform(match_df['country_name'])

if 'country_name_le' in match_df.columns:
    match_df.drop('country_name_le', axis = 1, inplace = True)

match_df.insert(0, 'country_name_le', xx)

set(zip(le.classes_, le.transform(le.classes_)))

{('Belgium', 0),
 ('England', 1),
 ('France', 2),
 ('Germany', 3),
 ('Italy', 4),
 ('Netherlands', 5),
 ('Poland', 6),
 ('Portugal', 7),
 ('Scotland', 8),
 ('Spain', 9),
 ('Switzerland', 10)}

In [24]:
match_df

,country_name_le,country_name,league_name,season,stage,date,home_team_long_name,home_short_long_name,away_team_long_name,away_short_long_name,home_team_goal,away_team_goal,total_goal,B365H,B365D,B365A
0,0,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-17,KRC Genk,GEN,Beerschot AC,BAC,1,1,2,1.73,3.40,5.00
1,0,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-16,SV Zulte-Waregem,ZUL,Sporting Lokeren,LOK,0,0,0,1.95,3.20,3.60
2,0,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-16,KSV Cercle Brugge,CEB,RSC Anderlecht,AND,0,3,3,2.38,3.30,2.75
3,0,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-17,KAA Gent,GEN,RAEC Mons,MON,5,0,5,1.44,3.75,7.50
4,0,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-16,FCV Dender EH,DEN,Standard de Liège,STL,1,3,4,5.00,3.50,1.65
5,0,Belgium,Belgium Jupiler League,2008/2009,1,2008-09-24,KV Mechelen,MEC,Club Brugge KV,CLB,1,1,2,4.75,3.40,1.67
6,0,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-16,KSV Roeselare,ROS,KV Kortrijk,KOR,2,2,4,2.10,3.20,3.30
7,0,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-16,Tubize,TUB,Royal Excel Mouscron,MOU,1,2,3,3.20,3.40,2.20
8,0,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-16,KVC Westerlo,WES,Sporting Charleroi,CHA,1,0,1,2.25,3.25,2.88
9,0,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-01,Club Brugge KV,CLB,KV Kortrijk,KOR,4,1,5,1.30,5.25,9.50
10,0,Belgium,Belgium Jupiler League,2008/2009,10,2008-10-31,Standard de Liège,STL,Sporting Charleroi,CHA,1,2,3,1.30,5.25,9.50
11,0,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-02,SV Zulte-Waregem,ZUL,KAA Gent,GEN,0,2,2,2.60,3.20,2.50
12,0,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-01,Sporting Lokeren,LOK,RAEC Mons,MON,0,0,0,1.91,3.40,4.00
13,0,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-01,FCV Dender EH,DEN,KVC Westerlo,WES,2,2,4,2.90,3.30,2.38
14,0,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-01,KV Mechelen,MEC,KSV Roeselare,ROS,1,2,3,1.70,3.30,4.50
15,0,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-01,Royal Excel Mouscron,MOU,KSV Cercle Brugge,CEB,0,1,1,2.35,3.30,3.00
16,0,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-01,Tubize,TUB,KRC Genk,GEN,1,3,4,6.00,3.75,1.57
17,0,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-02,Beerschot AC,BAC,RSC Anderlecht,AND,1,3,4,4.00,3.25,1.83
18,0,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-08,RSC Anderlecht,AND,Sporting Lokeren,LOK,2,3,5,1.36,4.75,8.50
19,0,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-08,RAEC Mons,MON,Royal Excel Mouscron,MOU,0,0,0,2.40,3.30,2.90
20,0,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-09,Sporting Charleroi,CHA,Club Brugge KV,CLB,2,2,4,3.20,3.30,2.25
21,0,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-07,KSV Cercle Brugge,CEB,SV Zulte-Waregem,ZUL,2,0,2,1.75,3.75,4.33
22,0,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-08,KAA Gent,GEN,FCV Dender EH,DEN,1,1,2,1.40,4.33,8.00
23,0,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-08,KSV Roeselare,ROS,Tubize,TUB,1,2,3,1.83,3.50,4.20
24,0,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-08,KV Kortrijk,KOR,KV Mechelen,MEC,0,0,0,2.00,3.50,3.60
25,0,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-08,KVC Westerlo,WES,KRC Genk,GEN,1,0,1,2.70,3.25,2.60
26,0,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-09,Beerschot AC,BAC,Standard de Liège,STL,1,3,4,3.60,3.30,2.05
27,0,Belgium,Belgium Jupiler League,2008/2009,12,2008-11-16,Club Brugge KV,CLB,RSC Anderlecht,AND,1,1,2,2.30,3.25,2.90
28,0,Belgium,Belgium Jupiler League,2008/2009,12,2008-11-15,KRC Genk,GEN,KSV Roeselare,ROS,1,1,2,1.25,5.25,10.00
29,0,Belgium,Belgium Jupiler League,2008/2009,12,2008-11-15,SV Zulte-Waregem,ZUL,Beerschot AC,BAC,2,2,4,2.00,3.25,3.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25949,10,Switzerland,Switzerland Super League,2015/2016,4,2015-08-08,Grasshopper Club Zürich,GRA,Lugano,LUG,6,1,7,0.00,0.00,0.00
25950,10,Switzerland,Switzerland Super League,2015/2016,4,2015-08-08,FC Luzern,LUZ,FC Basel,BAS,1,3,4,0.00,0.00,0.00
25951,10,Switzerland,Switzerland Super League,2015/2016,4,2015-08-09,FC St. Gallen,GAL,FC Zürich,ZUR,0,2,2,0.00,0.00,0.00
25952,10,Switzerland,Switzerland Super League,2015/2016,4,2015-08-09,FC Vaduz,VAD,FC Sion,SIO,1,1,2,0.00,0.00,0.00
25953,10,Switzerland,Switzerland Super League,2015/2016,4,2015-08-09,BSC Young Boys,YB,FC Thun,THU,3,1,4,0.00,0.00,0.00
25954,10,Switzerland,Switzerland Super League,2015/2016,5,2015-08-12,FC Basel,BAS,FC Thun,THU,3,1,4,0.00,0.00,0.00
25955,10,Switzerland,Switzerland Super League,2015/2016,5,2015-08-12,BSC Young Boys,YB,Lugano,LUG,0,1,1,0.00,0.00,0.00
25956,10,Switzerland,Switzerland Super League,2015/2016,5,2015-08-12,FC Luzern,LUZ,FC St. Gallen,GAL,0,1,1,0.00,0.00,0.00
25957,10,Switzerland,Switzerland Super League,2015/2016,5,2015-08-13,FC Sion,SIO,FC Zürich,ZUR,3,1,4,0.00,0.00,0.00
25958,10,Switzerland,Switzerland Super League,2015/2016,5,2015-08-13,FC Vaduz,VAD,Grasshopper Club Zürich,GRA,3,3,6,0.00,0.00,0.00
25959,10,Switzerland,Switzerland Super League,2015/2016,6,2015-08-22,Lugano,LUG,FC Basel,BAS,1,3,4,0.00,0.00,0.00
25960,10,Switzerland,Switzerland Super League,2015/2016,6,2015-08-23,FC Sion,SIO,BSC Young Boys,YB,1,3,4,0.00,0.00,0.00
25961,10,Switzerland,Switzerland Super League,2015/2016,6,2015-08-23,FC St. Gallen,GAL,Grasshopper Club Zürich,GRA,0,2,2,0.00,0.00,0.00
25962,10,Switzerland,Switzerland Super League,2015/2016,6,2015-08-23,FC Thun,THU,FC Vaduz,VAD,1,0,1,0.00,0.00,0.00
25963,10,Switzerland,Switzerland Super League,2015/2016,6,2015-08-22,FC Zürich,ZUR,FC Luzern,LUZ,2,5,7,0.00,0.00,0.00
25964,10,Switzerland,Switzerland Super League,2015/2016,7,2015-08-29,Lugano,LUG,FC Luzern,LUZ,0,1,1,0.00,0.00,0.00
25965,10,Switzerland,Switzerland Super League,2015/2016,7,2015-08-29,FC Vaduz,VAD,FC St. Gallen,GAL,1,0,1,0.00,0.00,0.00
25966,10,Switzerland,Switzerland Super League,2015/2016,7,2015-08-30,FC Thun,THU,FC Sion,SIO,0,2,2,0.00,0.00,0.00
25967,10,Switzerland,Switzerland Super League,2015/2016,7,2015-08-30,FC Basel,BAS,FC Zürich,ZUR,3,1,4,0.00,0.00,0.00
25968,10,Switzerland,Switzerland Super League,2015/2016,7,2015-08-30,Grasshopper Club Zürich,GRA,BSC Young Boys,YB,3,2,5,0.00,0.00,0.00
25969,10,Switzerland,Switzerland Super League,2015/2016,8,2015-09-12,FC Basel,BAS,FC St. Gallen,GAL,2,1,3,0.00,0.00,0.00
25970,10,Switzerland,Switzerland Super League,2015/2016,8,2015-09-12,BSC Young Boys,YB,FC Vaduz,VAD,4,0,4,0.00,0.00,0.00
25971,10,Switzerland,Switzerland Super League,2015/2016,8,2015-09-13,FC Luzern,LUZ,Grasshopper Club Zürich,GRA,3,3,6,0.00,0.00,0.00
25972,10,Switzerland,Switzerland Super League,2015/2016,8,2015-09-13,FC Zürich,ZUR,FC Thun,THU,3,3,6,0.00,0.00,0.00
25973,10,Switzerland,Switzerland Super League,2015/2016,8,2015-09-13,FC Sion,SIO,Lugano,LUG,3,0,3,0.00,0.00,0.00
25974,10,Switzerland,Switzerland Super League,2015/2016,9,2015-09-22,FC St. Gallen,GAL,FC Thun,THU,1,0,1,0.00,0.00,0.00
25975,10,Switzerland,Switzerland Super League,2015/2016,9,2015-09-23,FC Vaduz,VAD,FC Luzern,LUZ,1,2,3,0.00,0.00,0.00
25976,10,Switzerland,Switzerland Super League,2015/2016,9,2015-09-23,Grasshopper Club Zürich,GRA,FC Sion,SIO,2,0,2,0.00,0.00,0.00
25977,10,Switzerland,Switzerland Super League,2015/2016,9,2015-09-22,Lugano,LUG,FC Zürich,ZUR,0,0,0,0.00,0.00,0.00
25978,10,Switzerland,Switzerland Super League,2015/2016,9,2015-09-23,BSC Young Boys,YB,FC Basel,BAS,4,3,7,0.00,0.00,0.00